//! Render every discovered artifact into a [`Page`] (path + content, relative to the catalog
//! output root — which mirrors the `--input` tree 1:1, extensions swapped for `.md`), write
//! them (preserving hand-written manual notes below the sentinel), or diff them for `--check`.

pub mod bpmn;
pub mod coverage;
pub mod dmn;
pub mod srl;
pub mod templates;
pub mod yaml_table;

use std::fmt::Write as _;
use std::path::Path;

use anyhow::Result;

use crate::manifest::{RulesManifest, TemplateManifest};
use crate::model::{DocTree, Package};
use crate::util::{basename, rel_link, with_md_ext};

const HEADER: &str = "<!-- Generated by rust/crates/sutra-docgen (authored-artifact \
catalog). Re-run via `cargo run -p sutra-cli -- docgen --input <folder> --output <dir>`. Do \
not edit above the MANUAL NOTES sentinel. -->";
const SENTINEL: &str = "<!-- MANUAL NOTES BELOW -->";
const NOTES_PLACEHOLDER: &str = "_Add hand-curated notes for this page here._";

/// A generated page: (catalog-output-relative POSIX path, content with default manual notes).
pub struct Page {
    pub path: String,
    pub content: String,
}

/// Render every page for a scan, in a deterministic (path-sorted) order.
pub fn generate_pages(tree: &DocTree) -> Vec<Page> {
    let mut pages = Vec::new();
    for pkg in &tree.packages {
        render_package(&tree.input_root, pkg, &mut pages);
    }
    // A single fallback root package (rel == ".") already owns "index.md" — otherwise
    // synthesize one root listing page so the catalog has one entry point.
    if !(tree.packages.len() == 1 && tree.packages[0].rel == ".") {
        pages.push(Page {
            path: "index.md".to_string(),
            content: render_root_index(tree),
        });
    }
    pages.sort_by(|a, b| a.path.cmp(&b.path));
    pages
}

/// Write all pages under `output`, preserving any existing manual notes. Returns the count.
pub fn write_all(output: &Path, pages: &[Page]) -> Result<usize> {
    for p in pages {
        let target = output.join(&p.path);
        if let Some(parent) = target.parent() {
            std::fs::create_dir_all(parent)?;
        }
        let final_content = preserve_manual_notes(&target, &p.content)?;
        let unchanged = std::fs::read_to_string(&target)
            .map(|on_disk| on_disk == final_content)
            .unwrap_or(false);
        if !unchanged {
            std::fs::write(&target, final_content)?;
        }
    }
    Ok(pages.len())
}

/// Write the raw generated content (default manual notes) into `root` — used only by `--check`.
pub fn write_raw(root: &Path, pages: &[Page]) -> Result<()> {
    for p in pages {
        let target = root.join(&p.path);
        if let Some(parent) = target.parent() {
            std::fs::create_dir_all(parent)?;
        }
        std::fs::write(&target, &p.content)?;
    }
    Ok(())
}

/// Compare freshly-generated pages against the committed tree. Returns the drifted page paths
/// (empty = in sync).
pub fn diff_against(
    generated_root: &Path,
    committed_root: &Path,
    pages: &[Page],
) -> Result<Vec<String>> {
    let mut drift = Vec::new();
    for p in pages {
        let gen_file = generated_root.join(&p.path);
        let committed_file = committed_root.join(&p.path);
        let gen_content = std::fs::read_to_string(&gen_file)?;
        if !committed_file.exists() {
            drift.push(format!("missing: {}", p.path));
            continue;
        }
        let expected = preserve_manual_notes(&committed_file, &gen_content)?;
        let actual = std::fs::read_to_string(&committed_file)?;
        if expected != actual {
            drift.push(format!("differs: {}", p.path));
        }
    }
    drift.sort();
    Ok(drift)
}

fn preserve_manual_notes(target: &Path, generated: &str) -> Result<String> {
    let Some(gen_idx) = generated.find(SENTINEL) else {
        return Ok(generated.to_string());
    };
    let existing = match std::fs::read_to_string(target) {
        Ok(s) => s,
        Err(_) => return Ok(generated.to_string()),
    };
    let Some(exist_idx) = existing.find(SENTINEL) else {
        return Ok(generated.to_string());
    };
    let gen_tail = gen_idx + SENTINEL.len();
    let exist_tail = exist_idx + SENTINEL.len();
    Ok(format!(
        "{}{}",
        &generated[..gen_tail],
        &existing[exist_tail..]
    ))
}

fn header(out: &mut String) {
    out.push_str(HEADER);
    out.push_str("\n\n");
}

fn footer(out: &mut String) {
    while out.ends_with('\n') {
        out.pop();
    }
    out.push_str("\n\n");
    out.push_str(SENTINEL);
    out.push_str("\n\n");
    out.push_str(NOTES_PLACEHOLDER);
    out.push('\n');
}

fn wrap_page(title: &str, source_rel: &str, body: &str) -> String {
    let mut out = String::new();
    header(&mut out);
    let _ = writeln!(out, "# {title}\n");
    let _ = writeln!(out, "**Source:** `{source_rel}`\n");
    out.push_str(body);
    footer(&mut out);
    out
}

fn wrap_error_page(kind: &str, source_rel: &str, err: &anyhow::Error) -> String {
    let mut out = String::new();
    header(&mut out);
    let _ = writeln!(out, "# {kind} — `{}`\n", basename(source_rel));
    let _ = writeln!(out, "**Source:** `{source_rel}`\n");
    out.push_str(
        "> **SUTRA-DOCGEN ERROR:** this file failed to parse; showing the error instead of a \
         rendered summary so one bad artifact doesn't block the whole catalog.\n\n",
    );
    let _ = writeln!(out, "```\n{err:#}\n```\n");
    footer(&mut out);
    out
}

// ---- package pages -----------------------------------------------------------------------

fn pkg_index_path(pkg: &Package) -> String {
    if pkg.rel == "." {
        "index.md".to_string()
    } else {
        format!("{}/index.md", pkg.rel)
    }
}

fn render_package(input_root: &Path, pkg: &Package, pages: &mut Vec<Page>) {
    // Merge every co-located rules-manifest / template-manifest into one lookup set (docgen
    // cross-reference is best-effort by file basename).
    let mut merged_rules = RulesManifest::default();
    for rel in &pkg.rules_manifest {
        if let Ok(text) = std::fs::read_to_string(input_root.join(rel)) {
            if let Ok(m) = RulesManifest::parse(&text) {
                merged_rules.rules.extend(m.rules);
            }
        }
    }
    let rules_manifest = (!merged_rules.rules.is_empty()).then_some(merged_rules);
    let mut merged_templates = TemplateManifest::default();
    for rel in &pkg.template_manifest {
        if let Ok(text) = std::fs::read_to_string(input_root.join(rel)) {
            if let Ok(m) = TemplateManifest::parse(&text) {
                merged_templates.templates.extend(m.templates);
            }
        }
    }
    let template_manifest = (!merged_templates.templates.is_empty()).then_some(merged_templates);

    for rel in &pkg.bpmn {
        let title = format!("BPMN process — `{}`", basename(rel));
        let content = match std::fs::read(input_root.join(rel)) {
            Ok(bytes) => match bpmn::render_bpmn_page(&bytes, rel) {
                Ok(body) => wrap_page(&title, rel, &body),
                Err(e) => wrap_error_page("BPMN", rel, &e),
            },
            Err(e) => wrap_error_page("BPMN", rel, &anyhow::anyhow!(e)),
        };
        pages.push(Page {
            path: with_md_ext(rel),
            content,
        });
    }

    for rel in &pkg.dmn {
        let title = format!("DMN rules — `{}`", basename(rel));
        let content = match std::fs::read(input_root.join(rel)) {
            Ok(bytes) => {
                match dmn::render_dmn_page(&bytes, rel, basename(rel), rules_manifest.as_ref()) {
                    Ok(body) => wrap_page(&title, rel, &body),
                    Err(e) => wrap_error_page("DMN", rel, &e),
                }
            }
            Err(e) => wrap_error_page("DMN", rel, &anyhow::anyhow!(e)),
        };
        pages.push(Page {
            path: with_md_ext(rel),
            content,
        });
    }

    for rel in &pkg.srl {
        let title = format!("Rules (`.srl`) — `{}`", basename(rel));
        let content = match std::fs::read_to_string(input_root.join(rel)) {
            Ok(text) => {
                match srl::render_srl_page(&text, rel, basename(rel), rules_manifest.as_ref()) {
                    Ok(body) => wrap_page(&title, rel, &body),
                    Err(e) => wrap_error_page("SRL", rel, &e),
                }
            }
            Err(e) => wrap_error_page("SRL", rel, &anyhow::anyhow!(e)),
        };
        pages.push(Page {
            path: with_md_ext(rel),
            content,
        });
    }

    for rel in &pkg.templates {
        let title = format!("Template — `{}`", basename(rel));
        let content = match std::fs::read_to_string(input_root.join(rel)) {
            Ok(text) => wrap_page(
                &title,
                rel,
                &templates::render_template_page(
                    &text,
                    rel,
                    basename(rel),
                    template_manifest.as_ref(),
                ),
            ),
            Err(e) => wrap_error_page("Template", rel, &anyhow::anyhow!(e)),
        };
        pages.push(Page {
            path: with_md_ext(rel),
            content,
        });
    }

    for rel in &pkg.coverage {
        pages.push(render_coverage_page(input_root, rel));
    }
    if let Some(rel) = &pkg.channels_yaml {
        pages.push(render_yaml_page(input_root, rel, "Channels"));
    }
    if let Some(rel) = &pkg.package_yaml {
        pages.push(render_yaml_page(input_root, rel, "Package"));
    }
    for rel in &pkg.other_yaml {
        pages.push(render_yaml_page(input_root, rel, "Config"));
    }

    pages.push(Page {
        path: pkg_index_path(pkg),
        content: render_package_index(pkg),
    });
}

/// Render one `coverage/**.yaml` cross-process coverage file as a first-class page (declared
/// correlation + coverage-route ids), falling back to the generic YAML table on an unexpected
/// shape. Mirrors [`render_yaml_page`] but with a coverage-aware body.
fn render_coverage_page(input_root: &Path, rel: &str) -> Page {
    let title = format!("Coverage — `{}`", basename(rel));
    let content = match std::fs::read_to_string(input_root.join(rel)) {
        Ok(text) => match serde_yaml::from_str::<serde_yaml::Value>(&text) {
            Ok(value) => wrap_page(&title, rel, &coverage::render_coverage_body(&value)),
            Err(e) => wrap_error_page("Coverage", rel, &anyhow::anyhow!(e)),
        },
        Err(e) => wrap_error_page("Coverage", rel, &anyhow::anyhow!(e)),
    };
    Page {
        path: with_md_ext(rel),
        content,
    }
}

fn render_yaml_page(input_root: &Path, rel: &str, kind: &str) -> Page {
    let title = format!("{kind} — `{}`", basename(rel));
    let content = match std::fs::read_to_string(input_root.join(rel)) {
        Ok(text) => match serde_yaml::from_str::<serde_yaml::Value>(&text) {
            Ok(value) => wrap_page(&title, rel, &yaml_table::render_yaml_body(&value)),
            Err(e) => wrap_error_page(kind, rel, &anyhow::anyhow!(e)),
        },
        Err(e) => wrap_error_page(kind, rel, &anyhow::anyhow!(e)),
    };
    Page {
        path: with_md_ext(rel),
        content,
    }
}

fn render_package_index(pkg: &Package) -> String {
    let from = pkg_index_path(pkg);
    let mut out = String::new();
    header(&mut out);
    let display = if pkg.rel == "." {
        "(input root)"
    } else {
        pkg.rel.as_str()
    };
    let _ = writeln!(out, "# Deployment package `{display}`\n");

    if let Some((tenant, module, version)) = pkg.tenant_module_version() {
        let _ = writeln!(
            out,
            "**Versioned-module layout:** tenant=`{tenant}` · module=`{module}` · version=`{version}`\n"
        );
    }

    section_links(&mut out, &from, "BPMN processes", &pkg.bpmn);
    section_links(&mut out, &from, "Rules (DMN)", &pkg.dmn);
    section_links(&mut out, &from, "Rules (SRL)", &pkg.srl);
    section_links(&mut out, &from, "Templates / scripts", &pkg.templates);

    // Conditional (unlike the always-rendered sections above) so packages without any coverage
    // artifact keep byte-identical index pages — coverage is a newer, optional artifact type.
    if !pkg.coverage.is_empty() {
        section_links(
            &mut out,
            &from,
            "Coverage routes (cross-process)",
            &pkg.coverage,
        );
    }

    out.push_str("## Configuration\n\n");
    let mut any_config = false;
    if let Some(rel) = &pkg.channels_yaml {
        let _ = writeln!(
            out,
            "- [`channels.yaml`]({})",
            rel_link(&from, &with_md_ext(rel))
        );
        any_config = true;
    }
    if let Some(rel) = &pkg.package_yaml {
        let _ = writeln!(
            out,
            "- [`package.yaml`]({})",
            rel_link(&from, &with_md_ext(rel))
        );
        any_config = true;
    }
    for rel in &pkg.rules_manifest {
        let _ = writeln!(
            out,
            "- `rules-manifest.yaml` (`{rel}`) — applicability shown on each DMN/SRL page"
        );
        any_config = true;
    }
    for rel in &pkg.template_manifest {
        let _ = writeln!(
            out,
            "- `template-manifest.yaml` (`{rel}`) — contract shown on each template page"
        );
        any_config = true;
    }
    for rel in &pkg.other_yaml {
        let _ = writeln!(
            out,
            "- [`{}`]({})",
            basename(rel),
            rel_link(&from, &with_md_ext(rel))
        );
        any_config = true;
    }
    if !any_config {
        out.push_str("_No configuration files._\n");
    }
    out.push('\n');

    if !pkg.other_files.is_empty() {
        out.push_str("## Other files\n\n");
        out.push_str(
            "_Discovered but not parsed by sutra-docgen (out of scope for this catalog)._\n\n",
        );
        out.push_str("| Path |\n|---|\n");
        for rel in &pkg.other_files {
            let _ = writeln!(out, "| `{rel}` |");
        }
        out.push('\n');
    }

    footer(&mut out);
    out
}

fn section_links(out: &mut String, from: &str, title: &str, rels: &[String]) {
    let _ = writeln!(out, "## {title}\n");
    if rels.is_empty() {
        out.push_str("_None._\n\n");
        return;
    }
    for rel in rels {
        let _ = writeln!(
            out,
            "- [`{}`]({})",
            basename(rel),
            rel_link(from, &with_md_ext(rel))
        );
    }
    out.push('\n');
}

// ---- root index ----------------------------------------------------------------------------

fn render_root_index(tree: &DocTree) -> String {
    let mut out = String::new();
    header(&mut out);
    let _ = writeln!(
        out,
        "# Authored-artifact catalog — `{}`\n",
        tree.input_display
    );
    out.push_str(
        "Generated by `sutra-docgen` — one deployment-package directory (a directory \
         containing `package.yaml`) per row; each links to its own index of BPMN/DMN/SRL/\
         template/channel pages.\n\n",
    );
    out.push_str("## Packages\n\n");
    if tree.packages.is_empty() {
        out.push_str("_No packages discovered under this input folder._\n\n");
    } else {
        out.push_str("| Package | Artifacts |\n|---|---|\n");
        for pkg in &tree.packages {
            let link = rel_link("index.md", &pkg_index_path(pkg));
            let count = pkg.bpmn.len()
                + pkg.dmn.len()
                + pkg.srl.len()
                + pkg.templates.len()
                + pkg.coverage.len();
            let _ = writeln!(
                out,
                "| [`{}`]({}) | {} artifact file(s) |",
                pkg.rel, link, count
            );
        }
        out.push('\n');
    }
    footer(&mut out);
    out
}
