//! Render every discovered artifact into a [`Page`] (path + content, relative to the catalog
//! output root — which mirrors the `--input` tree 1:1, extensions swapped for `.md`), write
//! them (preserving hand-written manual notes below the sentinel), or diff them for `--check`.

pub mod bpmn;
pub mod coverage;
pub mod diagram;
pub mod dmn;
pub mod srl;
pub mod templates;
pub mod yaml_table;

use std::collections::BTreeMap;
use std::fmt::Write as _;
use std::path::Path;

use anyhow::Result;

use crate::manifest::{RulesManifest, TemplateManifest};
use crate::model::{DocTree, Package};
use crate::util::{basename, rel_link, with_ext, with_md_ext};

const HEADER: &str = "<!-- Generated by rust/crates/sutra-docgen (authored-artifact \
catalog). Re-run via `sutra generate docs --input <folder> --output <dir>`. Do \
not edit above the MANUAL NOTES sentinel. -->";
const SENTINEL: &str = "<!-- MANUAL NOTES BELOW -->";
/// The same contract for `book.toml`, which is configuration as well as derivation. TOML has no
/// HTML comments, so the sentinel is a `#` comment instead.
const TOML_SENTINEL: &str = "# --- MANUAL SETTINGS BELOW (regeneration preserves them) ---";
const NOTES_PLACEHOLDER: &str = "_Add hand-curated notes for this page here._";

/// A generated page: (catalog-output-relative POSIX path, content with default manual notes).
pub struct Page {
    pub path: String,
    pub content: String,
}

/// Render every page for a scan, in a deterministic (path-sorted) order.
///
/// The mdBook scaffolding (`SUMMARY.md`, `book.toml`) is part of the page set, so the catalog is
/// a buildable book the moment it is generated — `mdbook build <output>` needs nothing added by
/// hand — and both files are drift-gated by `--check` exactly like every page they index.
pub fn generate_pages(tree: &DocTree) -> Vec<Page> {
    let mut pages = Vec::new();
    for pkg in &tree.packages {
        render_package(&tree.input_root, pkg, &mut pages);
    }
    // A single fallback root package (rel == ".") already owns "index.md" — otherwise
    // synthesize one root listing page so the catalog has one entry point.
    if !(tree.packages.len() == 1 && tree.packages[0].rel == ".") {
        pages.push(Page {
            path: "index.md".to_string(),
            content: render_root_index(tree),
        });
    }
    pages.sort_by(|a, b| a.path.cmp(&b.path));
    // Appended AFTER the sort so the scaffolding is derived from the final page set, and pushed
    // last so it never perturbs the deterministic page order above.
    pages.push(Page {
        path: "SUMMARY.md".to_string(),
        content: render_summary(&pages),
    });
    pages.push(Page {
        path: "book.toml".to_string(),
        content: render_book_toml(tree),
    });
    pages
}

/// mdBook's table of contents, derived from the generated page set.
///
/// Derived, never hand-written: `mdbook build` fails on a `SUMMARY.md` entry with no file behind
/// it, an unlisted page is silently not rendered, and a hand-maintained list is exactly the thing
/// that rots as artifacts come and go. Titles come from each page's own `# ` line, so the book
/// and the page can never disagree about what a page is called.
///
/// Structure follows the catalog's own shape: `index.md` is the landing page, each top-level
/// folder becomes an mdBook *part* (a `#` line in SUMMARY), and a folder nested inside one — the
/// per-codec `schemas/<codec>/` directories — becomes a draft parent (`[name]()`, unclickable)
/// so its pages nest under something. Indentation without a parent item is not a hierarchy
/// mdBook understands, and two `codec-manifest.yaml` pages would otherwise be indistinguishable.
///
/// No MANUAL NOTES sentinel: mdBook parses this file strictly, and trailing prose breaks the
/// build. It is the one generated file with nothing hand-editable in it.
fn render_summary(pages: &[Page]) -> String {
    let mut out = String::from("# Summary\n\n");
    if let Some(index) = pages.iter().find(|p| p.path == "index.md") {
        let _ = writeln!(out, "[{}](index.md)\n", title_of(index));
    }

    // Section order is the reading order of a package: what it runs, then what it decides with,
    // then what it answers with, then what it speaks, then how it is wired.
    const ORDER: [(&str, &str); 5] = [
        ("bpmn", "Processes"),
        ("rules", "Rules"),
        ("templates", "Templates"),
        ("schemas", "Schemas"),
        ("", "Package configuration"),
    ];

    let mut sections: BTreeMap<&str, Vec<&Page>> = BTreeMap::new();
    for page in pages {
        if !page.path.ends_with(".md") || page.path == "index.md" || page.path == "SUMMARY.md" {
            continue;
        }
        let head = page.path.split_once('/').map(|(h, _)| h).unwrap_or("");
        sections.entry(head).or_default().push(page);
    }

    let mut seen: Vec<&str> = Vec::new();
    for (key, title) in ORDER {
        if let Some(group) = sections.get(key) {
            write_section(&mut out, title, group);
            seen.push(key);
        }
    }
    // Anything the fixed order does not name still gets a part, alphabetically — a new artifact
    // kind must never fall out of the book just because this list was not updated.
    for (key, group) in &sections {
        if !seen.contains(key) {
            write_section(&mut out, key, group);
        }
    }
    out
}

/// One mdBook part: a `#` title, then its pages — nesting a per-codec folder under a draft parent.
fn write_section(out: &mut String, title: &str, group: &[&Page]) {
    let _ = writeln!(out, "# {title}\n");
    let mut open_parent: Option<String> = None;
    for page in group {
        // `schemas/fednow/codec-manifest.md` -> parent "fednow"; anything shallower has none.
        let parent = page
            .path
            .rsplit_once('/')
            .map(|(dir, _)| dir)
            .and_then(|dir| dir.split_once('/').map(|(_, rest)| rest.to_string()));
        if parent != open_parent {
            if let Some(name) = &parent {
                let _ = writeln!(out, "- [{name}]()");
            }
            open_parent = parent.clone();
        }
        let indent = if parent.is_some() { "  " } else { "" };
        let _ = writeln!(out, "{indent}- [{}]({})", title_of(page), page.path);
    }
    out.push('\n');
}

/// The page's own `# ` heading — the title `wrap_page` already chose. Falls back to the path so a
/// malformed page still gets a usable entry rather than an empty link.
fn title_of(page: &Page) -> String {
    page.content
        .lines()
        .find_map(|l| l.strip_prefix("# "))
        .map(|t| t.trim().replace('[', "\\[").replace(']', "\\]"))
        .unwrap_or_else(|| page.path.clone())
}

/// A minimal `book.toml`. `src = "."` keeps the pages where they already are — the catalog IS the
/// book's source tree, so nothing has to be copied or restructured to publish it.
///
/// Unlike every other generated file this one is also CONFIGURATION — a title, a theme, a repo
/// URL are the author's to choose. So it carries the same contract the pages do, with a TOML
/// comment for a sentinel: everything above [`TOML_SENTINEL`] is regenerated, everything below is
/// preserved. Put your `[output.html]` overrides there and regeneration will leave them alone.
fn render_book_toml(tree: &DocTree) -> String {
    let title = match tree.packages.as_slice() {
        [one] if one.rel != "." => format!("{} — deployment catalog", one.rel),
        _ => "Deployment catalog".to_string(),
    };
    format!(
        "# Generated by rust/crates/sutra-docgen (authored-artifact catalog). Re-run via\n\
# `sutra generate docs --input <folder> --output <dir>`. Do not edit above the sentinel.\n\
[book]\n\
title = \"{title}\"\n\
src = \".\"\n\
\n\
{TOML_SENTINEL}\n\
\n\
[output.html]\n\
default-theme = \"light\"\n"
    )
}

/// Write all pages under `output`, preserving any existing manual notes. Returns the count.
pub fn write_all(output: &Path, pages: &[Page]) -> Result<usize> {
    for p in pages {
        let target = output.join(&p.path);
        if let Some(parent) = target.parent() {
            std::fs::create_dir_all(parent)?;
        }
        let final_content = preserve_manual_notes(&target, &p.content)?;
        let unchanged = std::fs::read_to_string(&target)
            .map(|on_disk| on_disk == final_content)
            .unwrap_or(false);
        if !unchanged {
            std::fs::write(&target, final_content)?;
        }
    }
    Ok(pages.len())
}

/// Write the raw generated content (default manual notes) into `root` — used only by `--check`.
pub fn write_raw(root: &Path, pages: &[Page]) -> Result<()> {
    for p in pages {
        let target = root.join(&p.path);
        if let Some(parent) = target.parent() {
            std::fs::create_dir_all(parent)?;
        }
        std::fs::write(&target, &p.content)?;
    }
    Ok(())
}

/// Compare freshly-generated pages against the committed tree. Returns the drifted page paths
/// (empty = in sync).
pub fn diff_against(
    generated_root: &Path,
    committed_root: &Path,
    pages: &[Page],
) -> Result<Vec<String>> {
    let mut drift = Vec::new();
    for p in pages {
        let gen_file = generated_root.join(&p.path);
        let committed_file = committed_root.join(&p.path);
        let gen_content = std::fs::read_to_string(&gen_file)?;
        if !committed_file.exists() {
            drift.push(format!("missing: {}", p.path));
            continue;
        }
        let expected = preserve_manual_notes(&committed_file, &gen_content)?;
        let actual = std::fs::read_to_string(&committed_file)?;
        if expected != actual {
            drift.push(format!("differs: {}", p.path));
        }
    }
    drift.sort();
    Ok(drift)
}

/// Which sentinel marks the hand-editable tail of this file — `#` for TOML, an HTML comment for
/// everything else (markdown).
fn sentinel_for(target: &Path) -> &'static str {
    match target.extension().and_then(|e| e.to_str()) {
        Some("toml") => TOML_SENTINEL,
        _ => SENTINEL,
    }
}

fn preserve_manual_notes(target: &Path, generated: &str) -> Result<String> {
    let sentinel = sentinel_for(target);
    let Some(gen_idx) = generated.find(sentinel) else {
        return Ok(generated.to_string());
    };
    let existing = match std::fs::read_to_string(target) {
        Ok(s) => s,
        Err(_) => return Ok(generated.to_string()),
    };
    let Some(exist_idx) = existing.find(sentinel) else {
        return Ok(generated.to_string());
    };
    let gen_tail = gen_idx + sentinel.len();
    let exist_tail = exist_idx + sentinel.len();
    Ok(format!(
        "{}{}",
        &generated[..gen_tail],
        &existing[exist_tail..]
    ))
}

fn header(out: &mut String) {
    out.push_str(HEADER);
    out.push_str("\n\n");
}

fn footer(out: &mut String) {
    while out.ends_with('\n') {
        out.pop();
    }
    out.push_str("\n\n");
    out.push_str(SENTINEL);
    out.push_str("\n\n");
    out.push_str(NOTES_PLACEHOLDER);
    out.push('\n');
}

fn wrap_page(title: &str, source_rel: &str, body: &str) -> String {
    let mut out = String::new();
    header(&mut out);
    let _ = writeln!(out, "# {title}\n");
    let _ = writeln!(out, "**Source:** `{source_rel}`\n");
    out.push_str(body);
    footer(&mut out);
    out
}

fn wrap_error_page(kind: &str, source_rel: &str, err: &anyhow::Error) -> String {
    let mut out = String::new();
    header(&mut out);
    let _ = writeln!(out, "# {kind} — `{}`\n", basename(source_rel));
    let _ = writeln!(out, "**Source:** `{source_rel}`\n");
    out.push_str(
        "> **SUTRA-DOCGEN ERROR:** this file failed to parse; showing the error instead of a \
         rendered summary so one bad artifact doesn't block the whole catalog.\n\n",
    );
    let _ = writeln!(out, "```\n{err:#}\n```\n");
    footer(&mut out);
    out
}

// ---- package pages -----------------------------------------------------------------------

fn pkg_index_path(pkg: &Package) -> String {
    if pkg.rel == "." {
        "index.md".to_string()
    } else {
        format!("{}/index.md", pkg.rel)
    }
}

fn render_package(input_root: &Path, pkg: &Package, pages: &mut Vec<Page>) {
    // Merge every co-located rules-manifest / template-manifest into one lookup set (docgen
    // cross-reference is best-effort by file basename).
    let mut merged_rules = RulesManifest::default();
    for rel in &pkg.rules_manifest {
        if let Ok(text) = std::fs::read_to_string(input_root.join(rel)) {
            if let Ok(m) = RulesManifest::parse(&text) {
                merged_rules.rules.extend(m.rules);
            }
        }
    }
    let rules_manifest = (!merged_rules.rules.is_empty()).then_some(merged_rules);
    let mut merged_templates = TemplateManifest::default();
    for rel in &pkg.template_manifest {
        if let Ok(text) = std::fs::read_to_string(input_root.join(rel)) {
            if let Ok(m) = TemplateManifest::parse(&text) {
                merged_templates.templates.extend(m.templates);
            }
        }
    }
    let template_manifest = (!merged_templates.templates.is_empty()).then_some(merged_templates);

    for rel in &pkg.bpmn {
        let title = format!("BPMN process — `{}`", basename(rel));
        // The diagram is rendered once and used twice: scaled inline in the page, and as the
        // standalone `.svg` beside it that the page links for a full-size view.
        let svg_path = with_ext(rel, "svg");
        let svg_href = basename(&svg_path).to_string();
        let mut diagram_svg: Option<String> = None;
        let content = match std::fs::read(input_root.join(rel)) {
            Ok(bytes) => match bpmn::render_bpmn_page(&bytes, rel, &svg_href) {
                Ok(rendered) => {
                    diagram_svg = rendered.svg;
                    wrap_page(&title, rel, &rendered.body)
                }
                Err(e) => wrap_error_page("BPMN", rel, &e),
            },
            Err(e) => wrap_error_page("BPMN", rel, &anyhow::anyhow!(e)),
        };
        pages.push(Page {
            path: with_md_ext(rel),
            content,
        });
        if let Some(svg) = diagram_svg {
            pages.push(Page {
                path: svg_path,
                content: svg,
            });
        }
    }

    for rel in &pkg.dmn {
        let title = format!("DMN rules — `{}`", basename(rel));
        let content = match std::fs::read(input_root.join(rel)) {
            Ok(bytes) => {
                match dmn::render_dmn_page(&bytes, rel, basename(rel), rules_manifest.as_ref()) {
                    Ok(body) => wrap_page(&title, rel, &body),
                    Err(e) => wrap_error_page("DMN", rel, &e),
                }
            }
            Err(e) => wrap_error_page("DMN", rel, &anyhow::anyhow!(e)),
        };
        pages.push(Page {
            path: with_md_ext(rel),
            content,
        });
    }

    for rel in &pkg.srl {
        let title = format!("Rules (`.srl`) — `{}`", basename(rel));
        let content = match std::fs::read_to_string(input_root.join(rel)) {
            Ok(text) => {
                match srl::render_srl_page(&text, rel, basename(rel), rules_manifest.as_ref()) {
                    Ok(body) => wrap_page(&title, rel, &body),
                    Err(e) => wrap_error_page("SRL", rel, &e),
                }
            }
            Err(e) => wrap_error_page("SRL", rel, &anyhow::anyhow!(e)),
        };
        pages.push(Page {
            path: with_md_ext(rel),
            content,
        });
    }

    for rel in &pkg.templates {
        let title = format!("Template — `{}`", basename(rel));
        let content = match std::fs::read_to_string(input_root.join(rel)) {
            Ok(text) => wrap_page(
                &title,
                rel,
                &templates::render_template_page(
                    &text,
                    rel,
                    basename(rel),
                    template_manifest.as_ref(),
                ),
            ),
            Err(e) => wrap_error_page("Template", rel, &anyhow::anyhow!(e)),
        };
        pages.push(Page {
            path: with_md_ext(rel),
            content,
        });
    }

    for rel in &pkg.coverage {
        pages.push(render_coverage_page(input_root, rel));
    }
    if let Some(rel) = &pkg.channels_yaml {
        pages.push(render_yaml_page(input_root, rel, "Channels"));
    }
    if let Some(rel) = &pkg.package_yaml {
        pages.push(render_yaml_page(input_root, rel, "Package"));
    }
    for rel in &pkg.other_yaml {
        pages.push(render_yaml_page(input_root, rel, "Config"));
    }

    pages.push(Page {
        path: pkg_index_path(pkg),
        content: render_package_index(pkg),
    });
}

/// Render one `coverage/**.yaml` cross-process coverage file as a first-class page (declared
/// correlation + coverage-route ids), falling back to the generic YAML table on an unexpected
/// shape. Mirrors [`render_yaml_page`] but with a coverage-aware body.
fn render_coverage_page(input_root: &Path, rel: &str) -> Page {
    let title = format!("Coverage — `{}`", basename(rel));
    let content = match std::fs::read_to_string(input_root.join(rel)) {
        Ok(text) => match serde_yaml::from_str::<serde_yaml::Value>(&text) {
            Ok(value) => wrap_page(&title, rel, &coverage::render_coverage_body(&value)),
            Err(e) => wrap_error_page("Coverage", rel, &anyhow::anyhow!(e)),
        },
        Err(e) => wrap_error_page("Coverage", rel, &anyhow::anyhow!(e)),
    };
    Page {
        path: with_md_ext(rel),
        content,
    }
}

fn render_yaml_page(input_root: &Path, rel: &str, kind: &str) -> Page {
    let title = format!("{kind} — `{}`", basename(rel));
    let content = match std::fs::read_to_string(input_root.join(rel)) {
        Ok(text) => match serde_yaml::from_str::<serde_yaml::Value>(&text) {
            Ok(value) => wrap_page(&title, rel, &yaml_table::render_yaml_body(&value)),
            Err(e) => wrap_error_page(kind, rel, &anyhow::anyhow!(e)),
        },
        Err(e) => wrap_error_page(kind, rel, &anyhow::anyhow!(e)),
    };
    Page {
        path: with_md_ext(rel),
        content,
    }
}

fn render_package_index(pkg: &Package) -> String {
    let from = pkg_index_path(pkg);
    let mut out = String::new();
    header(&mut out);
    let display = if pkg.rel == "." {
        "(input root)"
    } else {
        pkg.rel.as_str()
    };
    let _ = writeln!(out, "# Deployment package `{display}`\n");

    if let Some((tenant, module, version)) = pkg.tenant_module_version() {
        let _ = writeln!(
            out,
            "**Versioned-module layout:** tenant=`{tenant}` · module=`{module}` · version=`{version}`\n"
        );
    }

    section_links(&mut out, &from, "BPMN processes", &pkg.bpmn);
    section_links(&mut out, &from, "Rules (DMN)", &pkg.dmn);
    section_links(&mut out, &from, "Rules (SRL)", &pkg.srl);
    section_links(&mut out, &from, "Templates / scripts", &pkg.templates);

    // Conditional (unlike the always-rendered sections above) so packages without any coverage
    // artifact keep byte-identical index pages — coverage is a newer, optional artifact type.
    if !pkg.coverage.is_empty() {
        section_links(
            &mut out,
            &from,
            "Coverage routes (cross-process)",
            &pkg.coverage,
        );
    }

    out.push_str("## Configuration\n\n");
    let mut any_config = false;
    if let Some(rel) = &pkg.channels_yaml {
        let _ = writeln!(
            out,
            "- [`channels.yaml`]({})",
            rel_link(&from, &with_md_ext(rel))
        );
        any_config = true;
    }
    if let Some(rel) = &pkg.package_yaml {
        let _ = writeln!(
            out,
            "- [`package.yaml`]({})",
            rel_link(&from, &with_md_ext(rel))
        );
        any_config = true;
    }
    for rel in &pkg.rules_manifest {
        let _ = writeln!(
            out,
            "- `rules-manifest.yaml` (`{rel}`) — applicability shown on each DMN/SRL page"
        );
        any_config = true;
    }
    for rel in &pkg.template_manifest {
        let _ = writeln!(
            out,
            "- `template-manifest.yaml` (`{rel}`) — contract shown on each template page"
        );
        any_config = true;
    }
    for rel in &pkg.other_yaml {
        let _ = writeln!(
            out,
            "- [`{}`]({})",
            basename(rel),
            rel_link(&from, &with_md_ext(rel))
        );
        any_config = true;
    }
    if !any_config {
        out.push_str("_No configuration files._\n");
    }
    out.push('\n');

    if !pkg.other_files.is_empty() {
        out.push_str("## Other files\n\n");
        out.push_str(
            "_Discovered but not parsed by sutra-docgen (out of scope for this catalog)._\n\n",
        );
        out.push_str("| Path |\n|---|\n");
        for rel in &pkg.other_files {
            let _ = writeln!(out, "| `{rel}` |");
        }
        out.push('\n');
    }

    footer(&mut out);
    out
}

fn section_links(out: &mut String, from: &str, title: &str, rels: &[String]) {
    let _ = writeln!(out, "## {title}\n");
    if rels.is_empty() {
        out.push_str("_None._\n\n");
        return;
    }
    for rel in rels {
        let _ = writeln!(
            out,
            "- [`{}`]({})",
            basename(rel),
            rel_link(from, &with_md_ext(rel))
        );
    }
    out.push('\n');
}

// ---- root index ----------------------------------------------------------------------------

fn render_root_index(tree: &DocTree) -> String {
    let mut out = String::new();
    header(&mut out);
    let _ = writeln!(
        out,
        "# Authored-artifact catalog — `{}`\n",
        tree.input_display
    );
    out.push_str(
        "Generated by `sutra-docgen` — one deployment-package directory (a directory \
         containing `package.yaml`) per row; each links to its own index of BPMN/DMN/SRL/\
         template/channel pages.\n\n",
    );
    out.push_str("## Packages\n\n");
    if tree.packages.is_empty() {
        out.push_str("_No packages discovered under this input folder._\n\n");
    } else {
        out.push_str("| Package | Artifacts |\n|---|---|\n");
        for pkg in &tree.packages {
            let link = rel_link("index.md", &pkg_index_path(pkg));
            let count = pkg.bpmn.len()
                + pkg.dmn.len()
                + pkg.srl.len()
                + pkg.templates.len()
                + pkg.coverage.len();
            let _ = writeln!(
                out,
                "| [`{}`]({}) | {} artifact file(s) |",
                pkg.rel, link, count
            );
        }
        out.push('\n');
    }
    footer(&mut out);
    out
}
