//! Render the catalog pages and write them (or diff them, for `--check`).
//!
//! Pages share the house style of the frozen reference-baseline catalog: a
//! `<!-- GENERATED … -->` sentinel, the summary, an
//! item inventory, a `## Relationships` table with bidirectional links, `## Stability`, and a
//! preserved `<!-- MANUAL NOTES BELOW -->` tail.

use std::collections::BTreeMap;
use std::fmt::Write as _;
use std::path::Path;

use crate::model::{Crate, ItemKind, SourceFile, Workspace};
use crate::resolve::{crate_page, file_page, workspace_page, Graph};
use crate::util::{cell, rel_link};

/// Page header sentinel. The mixed-case "Generated by" is deliberate: a now-retired sibling
/// generator once shared this output root and swept away any `.md` whose head carried the
/// all-caps `GENERATED by` marker but that it had not emitted that run — the case difference is
/// what let the two coexist in one tree. Those pages are a frozen snapshot today.
const HEADER: &str = "<!-- Generated by rust/crates/sutra-catalog-gen (syn-backed Rust \
catalog). Re-run via `make catalog`. Do not edit above the MANUAL NOTES sentinel. -->";

const SENTINEL: &str = "<!-- MANUAL NOTES BELOW -->";

const NOTES_PLACEHOLDER: &str = "_Add hand-curated notes for this page here._";

const STABILITY: &str = "Pre-GA — internal Rust workspace crate. Not published (`publish = \
false`); the API surface is still evolving. Generated by `sutra-catalog-gen` — do not hand-edit \
above the MANUAL NOTES sentinel.";

/// A generated page: (catalog-output-relative path, content with default manual notes).
pub struct Page {
    pub path: String,
    pub content: String,
}

/// Render every catalog page for the workspace, in a deterministic order.
pub fn generate_pages(ws: &Workspace, g: &Graph) -> Vec<Page> {
    let ctx = Ctx::new(ws, g);
    let mut pages = Vec::new();

    pages.push(Page {
        path: workspace_page(),
        content: render_workspace(&ctx),
    });

    for c in &ws.crates {
        pages.push(Page {
            path: crate_page(c),
            content: render_crate(&ctx, c),
        });
        for f in &c.files {
            pages.push(Page {
                path: file_page(c, &f.rel),
                content: render_file(&ctx, c, f),
            });
        }
    }

    pages.sort_by(|a, b| a.path.cmp(&b.path));
    pages
}

/// Write all pages under `output`, preserving any existing manual notes. Returns the count.
pub fn write_all(output: &Path, pages: &[Page]) -> anyhow::Result<usize> {
    for p in pages {
        let target = output.join(&p.path);
        if let Some(parent) = target.parent() {
            std::fs::create_dir_all(parent)?;
        }
        let final_content = preserve_manual_notes(&target, &p.content)?;
        // Write-if-changed keeps mtimes (and livereload) quiet.
        let unchanged = std::fs::read_to_string(&target)
            .map(|on_disk| on_disk == final_content)
            .unwrap_or(false);
        if !unchanged {
            std::fs::write(&target, final_content)?;
        }
    }
    Ok(pages.len())
}

/// Compare freshly-generated pages (already written into `generated_root`) against the committed
/// tree at `committed_root`. Returns the drifted page paths (empty = in sync).
pub fn diff_against(
    generated_root: &Path,
    committed_root: &Path,
    pages: &[Page],
) -> anyhow::Result<Vec<String>> {
    let mut drift = Vec::new();
    for p in pages {
        let gen_file = generated_root.join(&p.path);
        let committed_file = committed_root.join(&p.path);
        let gen_content = std::fs::read_to_string(&gen_file)?;
        if !committed_file.exists() {
            drift.push(format!("missing: {}", p.path));
            continue;
        }
        // Splice the committed file's manual notes into the generated content, exactly as a
        // real write would, so we compare the generated regions only.
        let expected = preserve_manual_notes(&committed_file, &gen_content)?;
        let actual = std::fs::read_to_string(&committed_file)?;
        if expected != actual {
            drift.push(format!("differs: {}", p.path));
        }
    }
    drift.sort();
    Ok(drift)
}

/// Splice the hand-written notes below `SENTINEL` from `target` (if it exists) into `generated`.
pub fn preserve_manual_notes(target: &Path, generated: &str) -> anyhow::Result<String> {
    let Some(gen_idx) = generated.find(SENTINEL) else {
        return Ok(generated.to_string());
    };
    let existing = match std::fs::read_to_string(target) {
        Ok(s) => s,
        Err(_) => return Ok(generated.to_string()),
    };
    let Some(exist_idx) = existing.find(SENTINEL) else {
        return Ok(generated.to_string());
    };
    let gen_tail = gen_idx + SENTINEL.len();
    let exist_tail = exist_idx + SENTINEL.len();
    Ok(format!(
        "{}{}",
        &generated[..gen_tail],
        &existing[exist_tail..]
    ))
}

// ---------------------------------------------------------------------------------------------
// Rendering context + page builders
// ---------------------------------------------------------------------------------------------

/// Read-only rendering context: name/page indices derived once.
struct Ctx<'a> {
    ws: &'a Workspace,
    g: &'a Graph,
    /// crate name → crate.
    by_name: BTreeMap<&'a str, &'a Crate>,
    /// file page path → short display label (`crate_ident::module::path`).
    labels: BTreeMap<String, String>,
}

impl<'a> Ctx<'a> {
    fn new(ws: &'a Workspace, g: &'a Graph) -> Self {
        let by_name = ws.crates.iter().map(|c| (c.name.as_str(), c)).collect();
        let mut labels = BTreeMap::new();
        for c in &ws.crates {
            for f in &c.files {
                labels.insert(file_page(c, &f.rel), display_module(c, f));
            }
        }
        Ctx {
            ws,
            g,
            by_name,
            labels,
        }
    }

    fn label(&self, page: &str) -> String {
        self.labels
            .get(page)
            .cloned()
            .unwrap_or_else(|| page.to_string())
    }
}

fn header(out: &mut String) {
    out.push_str(HEADER);
    out.push_str("\n\n");
}

/// Append the manual-notes tail with EXACTLY one blank line before the sentinel, whatever the
/// last section left behind — the byte-stable page tail the `--check` diff relies on.
fn footer(out: &mut String) {
    while out.ends_with('\n') {
        out.pop();
    }
    out.push_str("\n\n");
    out.push_str(SENTINEL);
    out.push_str("\n\n");
    out.push_str(NOTES_PLACEHOLDER);
    out.push('\n');
}

/// `crate_ident::module::path`; binaries display as their target name (the file stem).
fn display_module(c: &Crate, f: &SourceFile) -> String {
    if f.is_binary {
        return stem(&f.rel);
    }
    if f.module_path.is_empty() {
        c.ident.clone()
    } else {
        format!("{}::{}", c.ident, f.module_path.join("::"))
    }
}

fn stem(rel: &str) -> String {
    let name = rel.rsplit('/').next().unwrap_or(rel);
    name.strip_suffix(".rs").unwrap_or(name).to_string()
}

// ---- Workspace root page --------------------------------------------------------------------

fn render_workspace(ctx: &Ctx) -> String {
    let from = workspace_page();
    let mut out = String::new();
    header(&mut out);
    out.push_str("# Rust workspace (`rust/`)\n\n");
    out.push_str("**Manifest**: `rust/Cargo.toml`\n\n");
    out.push_str(
        "The Sutra Rust workspace. Each row links to a crate-index page (the crate's \
         `Cargo.toml`); every crate page in turn links to one page per source file under its \
         `src/`. Generated by `sutra-catalog-gen`.\n\n",
    );
    out.push_str("## Crates\n\n");
    out.push_str("| Crate | Description |\n|---|---|\n");
    for c in &ctx.ws.crates {
        let link = rel_link(&from, &crate_page(c));
        let desc = c.description.as_deref().unwrap_or("");
        let _ = writeln!(out, "| [`{}`]({}) | {} |", c.name, link, cell(desc));
    }
    footer(&mut out);
    out
}

// ---- Crate index page (Cargo.toml) ----------------------------------------------------------

fn render_crate(ctx: &Ctx, c: &Crate) -> String {
    let from = crate_page(c);
    let mut out = String::new();
    header(&mut out);
    let _ = writeln!(out, "# `{}` (Rust crate)\n", c.name);
    let _ = writeln!(out, "**Manifest**: `{}/Cargo.toml`\n", c.rel_dir);

    // Crate root link.
    if let Some(rootfile) = ["src/lib.rs", "src/main.rs"]
        .into_iter()
        .find(|r| c.files.iter().any(|f| f.rel == *r))
    {
        let link = rel_link(&from, &file_page(c, rootfile));
        let _ = writeln!(out, "**Crate root:** [`{rootfile}`]({link})\n");
    }

    if let Some(desc) = &c.description {
        let _ = writeln!(out, "{desc}\n");
    }

    // Source modules.
    out.push_str("## Source modules\n\n");
    if c.files.is_empty() {
        out.push_str("_No source files._\n\n");
    } else {
        out.push_str("| Module | Source |\n|---|---|\n");
        for f in &c.files {
            let link = rel_link(&from, &file_page(c, &f.rel));
            let _ = writeln!(
                out,
                "| `{}` | [`{}`]({}) |",
                display_module(c, f),
                f.rel,
                link
            );
        }
        out.push('\n');
    }

    // Relationships (crate-level dependency graph).
    out.push_str("## Relationships\n\n");
    let deps = ctx.g.crate_dep.get(&c.name);
    let depby = ctx.g.crate_depby.get(&c.name);
    let has = deps.is_some_and(|s| !s.is_empty()) || depby.is_some_and(|s| !s.is_empty());
    if has {
        out.push_str("| Relationship | Artifacts |\n|---|---|\n");
        row_crates(&mut out, "Depends on", &from, deps, ctx);
        row_crates(&mut out, "Depended on by", &from, depby, ctx);
        out.push('\n');
    } else {
        out.push_str("_No workspace-crate dependencies._\n\n");
    }

    out.push_str("## Stability\n\n");
    let _ = writeln!(out, "{STABILITY}\n");
    footer(&mut out);
    out
}

// ---- Source-file page -----------------------------------------------------------------------

fn render_file(ctx: &Ctx, c: &Crate, f: &SourceFile) -> String {
    let from = file_page(c, &f.rel);
    let mut out = String::new();
    header(&mut out);

    let kind = if f.is_binary {
        "Rust binary"
    } else {
        "Rust source"
    };
    let _ = writeln!(out, "# `{}` ({kind})\n", display_module(c, f));
    let _ = writeln!(out, "**Source**: `{}/{}`\n", c.rel_dir, f.rel);
    let crate_link = rel_link(&from, &crate_page(c));
    let _ = writeln!(out, "**Crate:** [`{}`]({})\n", c.name, crate_link);

    let module_path = if f.is_binary {
        "`(binary crate root)`".to_string()
    } else if f.module_path.is_empty() {
        "`crate` (crate root)".to_string()
    } else {
        format!("`crate::{}`", f.module_path.join("::"))
    };
    let _ = writeln!(out, "**Module path:** {module_path}\n");

    if let Some(doc) = &f.module_doc {
        let _ = writeln!(out, "{doc}\n");
    }

    render_items(&mut out, f);
    render_file_relationships(&mut out, ctx, f, &from);

    out.push_str("## Stability\n\n");
    let _ = writeln!(out, "{STABILITY}\n");
    footer(&mut out);
    out
}

fn render_items(out: &mut String, f: &SourceFile) {
    out.push_str("## Items\n\n");
    if f.items.is_empty() && f.methods.is_empty() {
        out.push_str("_This file declares no catalogued items._\n\n");
        return;
    }

    // Fixed kind order (Modules … Macros), each as its own subsection.
    for kind in [
        ItemKind::Module,
        ItemKind::Struct,
        ItemKind::Enum,
        ItemKind::Union,
        ItemKind::Trait,
        ItemKind::TypeAlias,
        ItemKind::Function,
        ItemKind::Constant,
        ItemKind::Static,
        ItemKind::Macro,
    ] {
        let group: Vec<_> = f.items.iter().filter(|i| i.kind == kind).collect();
        if group.is_empty() {
            continue;
        }
        let _ = writeln!(out, "### {}\n", kind.section_title());
        if kind == ItemKind::Function {
            out.push_str("| Visibility | Signature | Description |\n|---|---|---|\n");
            for i in group {
                let sig = i.signature.as_deref().unwrap_or(&i.name);
                let _ = writeln!(
                    out,
                    "| {} | `{}` | {} |",
                    vis_cell(&i.vis),
                    cell(sig),
                    cell(i.doc.as_deref().unwrap_or(""))
                );
            }
        } else {
            out.push_str("| Visibility | Name | Description |\n|---|---|---|\n");
            for i in group {
                let _ = writeln!(
                    out,
                    "| {} | `{}` | {} |",
                    vis_cell(&i.vis),
                    cell(&i.name),
                    cell(i.doc.as_deref().unwrap_or(""))
                );
            }
        }
        out.push('\n');
    }

    if !f.methods.is_empty() {
        out.push_str("### Methods\n\n");
        out.push_str("| Type | Visibility | Method | Description |\n|---|---|---|---|\n");
        for m in &f.methods {
            let _ = writeln!(
                out,
                "| `{}` | {} | `{}` | {} |",
                cell(&m.impl_ty),
                vis_cell(&m.vis),
                cell(&m.signature),
                cell(m.doc.as_deref().unwrap_or(""))
            );
        }
        out.push('\n');
    }
}

fn render_file_relationships(out: &mut String, ctx: &Ctx, f: &SourceFile, from: &str) {
    out.push_str("## Relationships\n\n");

    let implements: Vec<String> = f
        .trait_impls
        .iter()
        .map(|t| format!("`{}` for `{}`", t.trait_name, t.type_name))
        .collect();
    let refs = ctx.g.file_refs.get(from);
    let refby = ctx.g.file_refby.get(from);
    let uses_crate = ctx.g.file_uses_crate.get(from);

    let any = !implements.is_empty()
        || refs.is_some_and(|s| !s.is_empty())
        || refby.is_some_and(|s| !s.is_empty())
        || uses_crate.is_some_and(|s| !s.is_empty());
    if !any {
        out.push_str("_No catalogued relationships._\n\n");
        return;
    }

    out.push_str("| Relationship | Artifacts |\n|---|---|\n");
    if !implements.is_empty() {
        let _ = writeln!(out, "| Implements | {} |", implements.join(", "));
    }
    if let Some(set) = refs.filter(|s| !s.is_empty()) {
        let items: Vec<String> = set
            .iter()
            .map(|to| format!("[`{}`]({})", ctx.label(to), rel_link(from, to)))
            .collect();
        let _ = writeln!(out, "| References | {} |", items.join(", "));
    }
    if let Some(set) = refby.filter(|s| !s.is_empty()) {
        let items: Vec<String> = set
            .iter()
            .map(|to| format!("[`{}`]({})", ctx.label(to), rel_link(from, to)))
            .collect();
        let _ = writeln!(out, "| Referenced by | {} |", items.join(", "));
    }
    if let Some(set) = uses_crate.filter(|s| !s.is_empty()) {
        let items: Vec<String> = set
            .iter()
            .filter_map(|name| ctx.by_name.get(name.as_str()).map(|dc| (name, dc)))
            .map(|(name, dc)| format!("[`{}`]({})", name, rel_link(from, &crate_page(dc))))
            .collect();
        if !items.is_empty() {
            let _ = writeln!(out, "| Depends on crate | {} |", items.join(", "));
        }
    }
    out.push('\n');
}

fn row_crates(
    out: &mut String,
    label: &str,
    from: &str,
    set: Option<&std::collections::BTreeSet<String>>,
    ctx: &Ctx,
) {
    if let Some(set) = set.filter(|s| !s.is_empty()) {
        let items: Vec<String> = set
            .iter()
            .filter_map(|name| ctx.by_name.get(name.as_str()).map(|dc| (name, dc)))
            .map(|(name, dc)| format!("[`{}`]({})", name, rel_link(from, &crate_page(dc))))
            .collect();
        if !items.is_empty() {
            let _ = writeln!(out, "| {} | {} |", label, items.join(", "));
        }
    }
}

/// Visibility rendered for a table cell (`pub` in code font, private as an em dash).
fn vis_cell(vis: &str) -> String {
    if vis.is_empty() {
        "—".to_string()
    } else {
        format!("`{vis}`")
    }
}
