//! The Rust-emitting backend: one self-contained module per schema (model, lenient
//! decoder, canonical map projection, shape metadata) plus the cross-schema `registry.rs`
//! and `lib.rs`. It reproduces the upstream emitter this backend was ported from
//! byte-for-byte after `cargo fmt`, with the generated body comments phrased against the
//! contracts; the enum accessor is `canonical_name()`.
//!
//! Content-model nuance: choice components (named `*Choice` by ISO 20022 design rule) get
//! an exactly-one-member `check_choice` instead of `check_structure`, avoiding false
//! missing-element violations.

use std::collections::{BTreeMap, HashSet};
use std::fmt::Write as _;

use crate::model::{ClassModel, EnumModel, FieldModel, FieldType, ModuleInfo, ParseResult, Scalar};
use crate::names::{escape_rust, family, snake_case, variant_name};

macro_rules! w {
    ($dst:expr, $($arg:tt)*) => {{ let _ = write!($dst, $($arg)*); }};
}

pub const ISO_NS_PREFIX: &str = "urn:iso:std:iso:20022:tech:xsd:";

/// Generated-file header — contract-neutral, emitted verbatim.
const GEN_HEADER: &str = "// @generated by the sutra schema generator (XSD → Rust). DO NOT EDIT.\n";

/// Resolved plan for one field: how to declare, decode and project it.
struct FieldPlan<'a> {
    fm: &'a FieldModel,
    rust_name: String,
    scalar: Option<Scalar>,
    enum_type: Option<&'a str>,
    nested_type: Option<&'a str>,
    skip: bool,
}

/// The generation mode. **Slim** (default) emits the data-driven decode tables the
/// generic [`support::decode_document`] interpreter
/// walks — the form a generated binding crate normally commits. **Full** additionally emits the
/// typed message model (per-type structs + `decode_*` + `map_*`), opt-in via the CLI `--full`
/// flag for anyone who wants typed access.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Default)]
pub enum Mode {
    /// Data-driven tables only (the default; the slim committed crate).
    #[default]
    Slim,
    /// The full typed model as well (opt-in, not committed).
    Full,
}

/// The generator: accumulates per-schema [`ModuleInfo`] across `generate` calls, then
/// emits the cross-schema `registry.rs` / `lib.rs`.
pub struct Generator {
    modules: Vec<ModuleInfo>,
    feature_gating: bool,
    mode: Mode,
}

impl Default for Generator {
    fn default() -> Self {
        Generator {
            modules: Vec::new(),
            feature_gating: true,
            mode: Mode::Slim,
        }
    }
}

impl Generator {
    /// A generator in the default (slim) mode.
    pub fn new() -> Generator {
        Generator::default()
    }

    /// A generator in the given mode.
    pub fn with_mode(mode: Mode) -> Generator {
        Generator {
            mode,
            ..Generator::default()
        }
    }

    pub fn modules(&self) -> &[ModuleInfo] {
        &self.modules
    }

    /// The `#[cfg(feature = "…")]` line for a module, or empty when gating is off.
    fn cfg_line(&self, module: &str, indent: &str) -> String {
        if self.feature_gating {
            format!("{indent}#[cfg(feature = \"{}\")]\n", family(module))
        } else {
            String::new()
        }
    }

    /// Generate one Rust module file's content for `result` under module `module`,
    /// in the generator's configured [`Mode`].
    pub fn generate(&mut self, result: &ParseResult, module: &str) -> String {
        match self.mode {
            Mode::Slim => self.generate_slim(result, module),
            Mode::Full => self.generate_full(result, module),
        }
    }

    /// Emit the full typed model for one schema — structs + `decode_*` + `map_*` +
    /// shape metadata (the `--full` opt-in; not the committed form).
    fn generate_full(&mut self, result: &ParseResult, module: &str) -> String {
        let namespace = result.target_namespace.clone().unwrap_or_default();
        let message_type = match namespace.strip_prefix(ISO_NS_PREFIX) {
            Some(slug) => slug.to_string(),
            None => module.to_string(),
        };

        let class_names: HashSet<&str> = result.classes.iter().map(|c| c.name.as_str()).collect();
        let enum_names: HashSet<&str> = result.enums.iter().map(|e| e.name.as_str()).collect();

        let mut pool = FacetPool::new();
        let mut body = String::new();
        let mut shapes = String::new();

        for em in &result.enums {
            emit_enum(em, &mut body);
        }

        let mut root_rust_type: Option<String> = None;
        for cm in &result.classes {
            if root_rust_type.is_none() && cm.root_element_name.is_some() {
                root_rust_type = Some(cm.name.clone());
            }
            emit_class(
                cm,
                &class_names,
                &enum_names,
                &mut pool,
                &mut body,
                &mut shapes,
            );
        }

        let mut out = String::new();
        out.push_str(GEN_HEADER);
        w!(
            out,
            "//! {message_type} — model, lenient decoder, map projection and shape metadata.\n"
        );
        out.push_str("#![allow(non_camel_case_types)]\n");
        out.push_str("#![allow(clippy::upper_case_acronyms)]\n\n");
        out.push_str("use crate::support;\n\n");
        w!(
            out,
            "pub const NAMESPACE: &str = \"{}\";\n",
            escape_rust(&namespace)
        );
        w!(
            out,
            "pub const MESSAGE_TYPE: &str = \"{}\";\n\n",
            escape_rust(&message_type)
        );

        if let Some(root) = &root_rust_type {
            let root_class = result
                .classes
                .iter()
                .find(|c| &c.name == root)
                .expect("root class present");
            let root_element = root_class
                .root_element_name
                .as_deref()
                .expect("root element name present");
            let root_path = format!("/{root_element}");
            out.push_str("/// Lenient full-document decode. Hard-fails only on well-formedness\n");
            out.push_str(
                "/// (the well-formedness gate); every schema problem is a collected violation.\n",
            );
            w!(
                out,
                "pub fn decode(xml: &[u8]) -> Result<({root}, Vec<support::Violation>), support::ParseError> {{\n"
            );
            out.push_str("    let parsed = support::parse_document(xml)?;\n");
            out.push_str("    let mut ctx = support::Ctx::new(xml);\n");
            w!(
                out,
                "    if parsed.root.name != \"{}\" {{\n",
                escape_rust(root_element)
            );
            out.push_str("        let found = parsed.root.name.clone();\n");
            w!(
                out,
                "        ctx.violate(parsed.root.pos, \"/\", format!(\"expected root element '{}', found '{{found}}'\"));\n",
                escape_rust(root_element)
            );
            out.push_str("    }\n");
            out.push_str("    if parsed.namespace != NAMESPACE {\n");
            out.push_str("        let found = parsed.namespace.clone();\n");
            w!(
                out,
                "        ctx.violate(parsed.root.pos, \"{}\", format!(\"expected namespace '{{NAMESPACE}}', found '{{found}}'\"));\n",
                escape_rust(&root_path)
            );
            out.push_str("    }\n");
            w!(
                out,
                "    let doc = decode_{}(&parsed.root, \"{}\", &mut ctx);\n",
                snake_case(root),
                escape_rust(&root_path)
            );
            out.push_str("    Ok((doc, ctx.violations))\n");
            out.push_str("}\n\n");
        }

        out.push_str(&body);
        pool.emit(&mut out);

        out.push_str("/// Shape metadata (the navigation-shape contract): complex type name →\n");
        out.push_str("/// field table for deploy-time template-path checking.\n");
        out.push_str("pub static SHAPES: &[(&str, &[support::FieldShape])] = &[\n");
        out.push_str(&shapes);
        out.push_str("];\n\n");
        out.push_str(
            "pub fn shape_of(type_name: &str) -> Option<&'static [support::FieldShape]> {\n",
        );
        out.push_str(
            "    SHAPES.iter().find(|(n, _)| *n == type_name).map(|(_, fields)| *fields)\n",
        );
        out.push_str("}\n");

        self.modules.push(ModuleInfo {
            module_name: module.to_string(),
            namespace,
            message_type,
            root_rust_type,
        });
        out
    }

    /// Emit `registry.rs` from the accumulated modules, in the configured [`Mode`].
    pub fn registry(&self) -> String {
        match self.mode {
            Mode::Slim => self.registry_slim(),
            Mode::Full => self.registry_full(),
        }
    }

    /// Emit the full (typed) `registry.rs`: the `AnyDocument` enum over the typed
    /// documents plus the per-namespace decode/map match arms.
    fn registry_full(&self) -> String {
        let sorted: BTreeMap<&str, &ModuleInfo> = self
            .modules
            .iter()
            .filter(|m| m.root_rust_type.is_some())
            .map(|m| (m.module_name.as_str(), m))
            .collect();

        let mut out = String::new();
        out.push_str(GEN_HEADER);
        out.push_str("//! Slug→decoder registry: dispatches a document-element namespace to the\n");
        out.push_str("//! generated decoder. An unknown slug is a detectable\n");
        out.push_str("//! [`DecodeError::UnknownNamespace`] — the contract's could-not-validate\n");
        out.push_str("//! (schema-not-found) soft error. A non-well-formed body is the hard\n");
        out.push_str("//! [`DecodeError::NotWellFormed`] (the well-formedness gate).\n\n");
        out.push_str(
            "use crate::support::{self, FieldShape, MapValue, ParseError, Violation};\n\n",
        );
        w!(
            out,
            "pub const ISO20022_NS_PREFIX: &str = \"{ISO_NS_PREFIX}\";\n\n"
        );

        out.push_str("#[derive(Debug, Clone, PartialEq)]\n");
        out.push_str("pub enum AnyDocument {\n");
        for m in sorted.values() {
            out.push_str(&self.cfg_line(&m.module_name, "    "));
            let root = m.root_rust_type.as_deref().unwrap();
            w!(
                out,
                "    {}(Box<crate::{}::{}>),\n",
                variant_name(&m.module_name),
                m.module_name,
                root
            );
        }
        out.push_str("}\n\n");

        out.push_str("#[derive(Debug, Clone, PartialEq)]\n");
        out.push_str("pub struct Decoded {\n");
        out.push_str("    pub message_type: String,\n");
        out.push_str("    pub namespace: String,\n");
        out.push_str("    pub document: AnyDocument,\n");
        out.push_str("    pub violations: Vec<Violation>,\n");
        out.push_str("}\n\n");

        out.push_str("#[derive(Debug, Clone, PartialEq)]\n");
        out.push_str("pub enum DecodeError {\n");
        out.push_str(
            "    /// The document-element namespace has no generated decoder — detectable so\n",
        );
        out.push_str("    /// the codec can emit a soft \"could-not-validate\" and keep the payload routable.\n");
        out.push_str("    UnknownNamespace { namespace: String },\n");
        out.push_str("    /// The body is not well-formed XML (hard error).\n");
        out.push_str("    NotWellFormed(ParseError),\n");
        out.push_str("}\n\n");

        out.push_str("/// Every message type with a generated decoder, sorted by module name.\n");
        out.push_str("#[allow(unused_mut, clippy::let_and_return)]\n");
        out.push_str("pub fn message_types() -> Vec<&'static str> {\n");
        out.push_str("    let mut v: Vec<&'static str> = Vec::new();\n");
        let mut by_family: BTreeMap<&str, Vec<&ModuleInfo>> = BTreeMap::new();
        for m in sorted.values() {
            by_family.entry(family(&m.module_name)).or_default().push(m);
        }
        for (fam, list) in &by_family {
            w!(out, "    #[cfg(feature = \"{fam}\")]\n");
            out.push_str("    v.extend_from_slice(&[\n");
            for m in list {
                w!(out, "        crate::{}::MESSAGE_TYPE,\n", m.module_name);
            }
            out.push_str("    ]);\n");
        }
        out.push_str("    v\n");
        out.push_str("}\n\n");

        out.push_str("pub fn is_known_namespace(namespace: &str) -> bool {\n");
        out.push_str("    message_type_of(namespace).is_some()\n");
        out.push_str("}\n\n");

        out.push_str("/// The message-type slug for a known namespace: the tail of the\n");
        out.push_str("/// registry URN, e.g. `<prefix>order.001.001.01` → `order.001.001.01`.\n");
        out.push_str("pub fn message_type_of(namespace: &str) -> Option<&'static str> {\n");
        out.push_str("    match namespace {\n");
        for m in sorted.values() {
            out.push_str(&self.cfg_line(&m.module_name, "        "));
            w!(
                out,
                "        crate::{0}::NAMESPACE => Some(crate::{0}::MESSAGE_TYPE),\n",
                m.module_name
            );
        }
        out.push_str("        _ => None,\n");
        out.push_str("    }\n");
        out.push_str("}\n\n");

        out.push_str("/// Decode by sniffing the document element's namespace.\n");
        out.push_str("pub fn decode(xml: &[u8]) -> Result<Decoded, DecodeError> {\n");
        out.push_str("    let (namespace, _root) = support::sniff_root(xml).map_err(DecodeError::NotWellFormed)?;\n");
        out.push_str("    decode_for_namespace(&namespace, xml)\n");
        out.push_str("}\n\n");

        out.push_str("/// Decode against the decoder registered for `namespace`.\n");
        out.push_str("pub fn decode_for_namespace(namespace: &str, xml: &[u8]) -> Result<Decoded, DecodeError> {\n");
        out.push_str("    match namespace {\n");
        for m in sorted.values() {
            let var = variant_name(&m.module_name);
            out.push_str(&self.cfg_line(&m.module_name, "        "));
            w!(out, "        crate::{}::NAMESPACE => {{\n", m.module_name);
            w!(
                out,
                "            let (doc, violations) = crate::{}::decode(xml).map_err(DecodeError::NotWellFormed)?;\n",
                m.module_name
            );
            out.push_str("            Ok(Decoded {\n");
            w!(
                out,
                "                message_type: crate::{}::MESSAGE_TYPE.to_string(),\n",
                m.module_name
            );
            out.push_str("                namespace: namespace.to_string(),\n");
            w!(
                out,
                "                document: AnyDocument::{var}(Box::new(doc)),\n"
            );
            out.push_str("                violations,\n");
            out.push_str("            })\n");
            out.push_str("        }\n");
        }
        out.push_str("        _ => Err(DecodeError::UnknownNamespace { namespace: namespace.to_string() }),\n");
        out.push_str("    }\n");
        out.push_str("}\n\n");

        out.push_str("impl Decoded {\n");
        out.push_str("    /// Full document projection (envelope included).\n");
        out.push_str("    pub fn document_map(&self) -> MapValue {\n");
        out.push_str("        match &self.document {\n");
        for m in sorted.values() {
            out.push_str(&self.cfg_line(&m.module_name, "            "));
            w!(
                out,
                "            AnyDocument::{}(d) => crate::{}::map_{}(d),\n",
                variant_name(&m.module_name),
                m.module_name,
                snake_case(m.root_rust_type.as_deref().unwrap())
            );
        }
        if self.feature_gating {
            out.push_str("            #[allow(unreachable_patterns)]\n");
            out.push_str("            _ => unreachable!(\"no message-family feature enabled\"),\n");
        }
        out.push_str("        }\n");
        out.push_str("    }\n\n");
        out.push_str("    /// Business-message projection — the contract's body-map view\n");
        out.push_str("    /// (the single-child `<Document>` envelope unwrapped).\n");
        out.push_str("    pub fn body_map(&self) -> MapValue {\n");
        out.push_str("        support::unwrap_envelope(self.document_map())\n");
        out.push_str("    }\n");
        out.push_str("}\n\n");

        out.push_str(
            "/// Shape lookup across message types (deploy-time template-path checking).\n",
        );
        out.push_str("pub fn shape_of(message_type: &str, type_name: &str) -> Option<&'static [FieldShape]> {\n");
        out.push_str("    match message_type {\n");
        for m in sorted.values() {
            out.push_str(&self.cfg_line(&m.module_name, "        "));
            w!(
                out,
                "        crate::{0}::MESSAGE_TYPE => crate::{0}::shape_of(type_name),\n",
                m.module_name
            );
        }
        out.push_str("        _ => None,\n");
        out.push_str("    }\n");
        out.push_str("}\n\n");

        out.push_str(
            "/// The root (document) type name for a message type, for `shape_of` entry.\n",
        );
        out.push_str("pub fn root_type_name(message_type: &str) -> Option<&'static str> {\n");
        out.push_str("    match message_type {\n");
        for m in sorted.values() {
            out.push_str(&self.cfg_line(&m.module_name, "        "));
            w!(
                out,
                "        crate::{}::MESSAGE_TYPE => Some(\"{}\"),\n",
                m.module_name,
                escape_rust(m.root_rust_type.as_deref().unwrap())
            );
        }
        out.push_str("        _ => None,\n");
        out.push_str("    }\n");
        out.push_str("}\n");

        out
    }

    /// Emit `lib.rs` from the accumulated modules.
    pub fn lib(&self) -> String {
        let mut out = String::new();
        out.push_str(GEN_HEADER);
        out.push_str(
            "//! Self-contained generated message model: lenient decoders, canonical-projection\n",
        );
        out.push_str("//! map projections, and shape metadata. External deps: quick-xml, regex, bigdecimal.\n\n");
        out.push_str("pub mod support;\n");
        out.push_str("pub mod registry;\n");
        let sorted: BTreeMap<&str, ()> = self
            .modules
            .iter()
            .map(|m| (m.module_name.as_str(), ()))
            .collect();
        for name in sorted.keys() {
            out.push_str(&self.cfg_line(name, ""));
            w!(out, "pub mod {name};\n");
        }
        out
    }

    // -----------------------------------------------------------------------
    // Slim emission (data-driven decode tables — the committed default)
    // -----------------------------------------------------------------------

    /// Emit the slim module for one schema: the `TypeDecl` decode tables (walked by
    /// [`support::decode_document`]), the referenced enum value tables, the pooled
    /// facet set, and the (unchanged) shape metadata. No typed structs, no per-type
    /// `decode_*` / `map_*` — the generic interpreter reproduces their behaviour.
    fn generate_slim(&mut self, result: &ParseResult, module: &str) -> String {
        let namespace = result.target_namespace.clone().unwrap_or_default();
        let message_type = match namespace.strip_prefix(ISO_NS_PREFIX) {
            Some(slug) => slug.to_string(),
            None => module.to_string(),
        };

        let class_names: HashSet<&str> = result.classes.iter().map(|c| c.name.as_str()).collect();
        let enum_names: HashSet<&str> = result.enums.iter().map(|e| e.name.as_str()).collect();

        // Plan every class (mirrors `emit_class`'s field planning) and record which
        // enums are referenced (first-encounter order) and the root type.
        let mut type_plans: Vec<(&ClassModel, Vec<FieldPlan>, bool, bool)> = Vec::new();
        let mut referenced_enums: Vec<&str> = Vec::new();
        let mut root_rust_type: Option<String> = None;
        for cm in &result.classes {
            if root_rust_type.is_none() && cm.root_element_name.is_some() {
                root_rust_type = Some(cm.name.clone());
            }
            let mut plans: Vec<FieldPlan> = Vec::new();
            let mut used_names: HashSet<String> = HashSet::new();
            let mut has_any = false;
            for fm in &cm.fields {
                if fm.is_any_element {
                    has_any = true;
                    continue;
                }
                if fm.is_mixed || fm.has_substitution_members {
                    continue;
                }
                let p = plan_field(fm, &class_names, &enum_names, &mut used_names);
                if let Some(e) = p.enum_type {
                    if !referenced_enums.contains(&e) {
                        referenced_enums.push(e);
                    }
                }
                plans.push(p);
            }
            let is_choice = cm.xml_type_name.ends_with("Choice");
            type_plans.push((cm, plans, has_any, is_choice));
        }

        // Build the TYPES body + shape rows (this populates the facet pool).
        let mut pool = FacetPool::new();
        let mut types_body = String::new();
        let mut shapes = String::new();
        for (cm, plans, has_any, is_choice) in &type_plans {
            w!(types_body, "    support::TypeDecl {{\n");
            w!(types_body, "        name: \"{}\",\n", escape_rust(&cm.name));
            w!(types_body, "        is_choice: {is_choice},\n");
            w!(types_body, "        has_any: {has_any},\n");
            w!(types_body, "        fields: &[\n");
            for p in plans {
                emit_field_decl(p, &mut pool, &mut types_body);
            }
            w!(types_body, "        ],\n");
            w!(types_body, "    }},\n");
            emit_shape_row(cm, plans, &mut shapes);
        }

        let mut out = String::new();
        out.push_str(GEN_HEADER);
        w!(
            out,
            "//! {message_type} — data-driven decode tables (slim) and shape metadata.\n"
        );
        out.push_str("#![allow(non_upper_case_globals)]\n\n");
        out.push_str("use crate::support;\n\n");
        w!(
            out,
            "pub const NAMESPACE: &str = \"{}\";\n",
            escape_rust(&namespace)
        );
        w!(
            out,
            "pub const MESSAGE_TYPE: &str = \"{}\";\n",
            escape_rust(&message_type)
        );
        if let Some(root) = &root_rust_type {
            let root_class = result
                .classes
                .iter()
                .find(|c| &c.name == root)
                .expect("root class present");
            let root_element = root_class
                .root_element_name
                .as_deref()
                .expect("root element name present");
            w!(
                out,
                "pub const ROOT_ELEMENT: &str = \"{}\";\n",
                escape_rust(root_element)
            );
            w!(
                out,
                "pub const ROOT_TYPE: &str = \"{}\";\n",
                escape_rust(root)
            );
        }
        out.push('\n');

        // Pooled facet constants.
        pool.emit(&mut out);

        // Referenced enum value tables (xml_value → canonical_name).
        for e in &referenced_enums {
            let em = result
                .enums
                .iter()
                .find(|x| x.name.as_str() == *e)
                .expect("referenced enum present");
            w!(
                out,
                "static {}: &[(&str, &str)] = &[\n",
                enum_static_name(e)
            );
            for v in &em.values {
                w!(
                    out,
                    "    (\"{}\", \"{}\"),\n",
                    escape_rust(&v.xml_value),
                    escape_rust(&v.canonical_name)
                );
            }
            out.push_str("];\n");
        }
        if !referenced_enums.is_empty() {
            out.push('\n');
        }

        // The decode tables (one row per line — `rustfmt::skip` keeps the dense form
        // instead of exploding each `FieldDecl` across nine lines).
        out.push_str("/// Complex-type decode tables — the data-driven decoder walks these.\n");
        out.push_str("#[rustfmt::skip]\n");
        out.push_str("pub static TYPES: &[support::TypeDecl] = &[\n");
        out.push_str(&types_body);
        out.push_str("];\n\n");

        // Shape metadata (unchanged surface).
        out.push_str("/// Shape metadata (the navigation-shape contract): complex type name →\n");
        out.push_str("/// field table for deploy-time template-path checking.\n");
        out.push_str("#[rustfmt::skip]\n");
        out.push_str("pub static SHAPES: &[(&str, &[support::FieldShape])] = &[\n");
        out.push_str(&shapes);
        out.push_str("];\n\n");
        out.push_str(
            "pub fn shape_of(type_name: &str) -> Option<&'static [support::FieldShape]> {\n",
        );
        out.push_str(
            "    SHAPES.iter().find(|(n, _)| *n == type_name).map(|(_, fields)| *fields)\n",
        );
        out.push_str("}\n");

        self.modules.push(ModuleInfo {
            module_name: module.to_string(),
            namespace,
            message_type,
            root_rust_type,
        });
        out
    }

    /// Emit the slim `registry.rs`: a per-namespace `Schema` table (decode tables +
    /// shape fn) dispatched to the generic [`support::decode_document`].
    fn registry_slim(&self) -> String {
        let sorted: BTreeMap<&str, &ModuleInfo> = self
            .modules
            .iter()
            .filter(|m| m.root_rust_type.is_some())
            .map(|m| (m.module_name.as_str(), m))
            .collect();

        let mut out = String::new();
        out.push_str(GEN_HEADER);
        out.push_str(
            "//! Namespace→schema registry (slim, data-driven): dispatches a document-element\n",
        );
        out.push_str("//! namespace to that schema's decode tables and runs the generic decoder\n");
        out.push_str("//! ([`support::decode_document`]). An unknown namespace is a detectable\n");
        out.push_str(
            "//! [`DecodeError::UnknownNamespace`] (the schema-not-found soft error); a\n",
        );
        out.push_str("//! non-well-formed body is the hard [`DecodeError::NotWellFormed`].\n\n");
        out.push_str(
            "use crate::support::{self, FieldShape, MapValue, ParseError, TypeDecl, Violation};\n\n",
        );
        w!(
            out,
            "pub const ISO20022_NS_PREFIX: &str = \"{ISO_NS_PREFIX}\";\n\n"
        );

        out.push_str("/// One schema's decode + shape tables, keyed by namespace.\n");
        out.push_str("struct Schema {\n");
        out.push_str("    namespace: &'static str,\n");
        out.push_str("    message_type: &'static str,\n");
        out.push_str("    root_element: &'static str,\n");
        out.push_str("    root_type: &'static str,\n");
        out.push_str("    types: &'static [TypeDecl],\n");
        out.push_str("    shape_of: fn(&str) -> Option<&'static [FieldShape]>,\n");
        out.push_str("}\n\n");

        out.push_str("static SCHEMAS: &[Schema] = &[\n");
        for m in sorted.values() {
            out.push_str(&self.cfg_line(&m.module_name, "    "));
            w!(
                out,
                "    Schema {{ namespace: crate::{0}::NAMESPACE, message_type: crate::{0}::MESSAGE_TYPE, root_element: crate::{0}::ROOT_ELEMENT, root_type: crate::{0}::ROOT_TYPE, types: crate::{0}::TYPES, shape_of: crate::{0}::shape_of }},\n",
                m.module_name
            );
        }
        out.push_str("];\n\n");

        out.push_str("fn schema_for(namespace: &str) -> Option<&'static Schema> {\n");
        out.push_str("    SCHEMAS.iter().find(|s| s.namespace == namespace)\n");
        out.push_str("}\n\n");

        out.push_str("#[derive(Debug, Clone, PartialEq)]\n");
        out.push_str("pub struct Decoded {\n");
        out.push_str("    pub message_type: String,\n");
        out.push_str("    pub namespace: String,\n");
        out.push_str("    document: MapValue,\n");
        out.push_str("    pub violations: Vec<Violation>,\n");
        out.push_str("}\n\n");

        out.push_str("impl Decoded {\n");
        out.push_str("    /// Full document projection (envelope included).\n");
        out.push_str("    pub fn document_map(&self) -> MapValue {\n");
        out.push_str("        self.document.clone()\n");
        out.push_str("    }\n\n");
        out.push_str(
            "    /// Business-message projection — the single-child `<Document>` envelope unwrapped.\n",
        );
        out.push_str("    pub fn body_map(&self) -> MapValue {\n");
        out.push_str("        support::unwrap_envelope(self.document.clone())\n");
        out.push_str("    }\n");
        out.push_str("}\n\n");

        out.push_str("#[derive(Debug, Clone, PartialEq)]\n");
        out.push_str("pub enum DecodeError {\n");
        out.push_str(
            "    /// The document-element namespace has no bundled schema — detectable so\n",
        );
        out.push_str("    /// the codec can emit a soft \"could-not-validate\" and keep the payload routable.\n");
        out.push_str("    UnknownNamespace { namespace: String },\n");
        out.push_str("    /// The body is not well-formed XML (hard error).\n");
        out.push_str("    NotWellFormed(ParseError),\n");
        out.push_str("}\n\n");

        out.push_str("/// Every message type with a bundled schema, sorted by module name.\n");
        out.push_str("pub fn message_types() -> Vec<&'static str> {\n");
        out.push_str("    SCHEMAS.iter().map(|s| s.message_type).collect()\n");
        out.push_str("}\n\n");

        out.push_str("pub fn is_known_namespace(namespace: &str) -> bool {\n");
        out.push_str("    schema_for(namespace).is_some()\n");
        out.push_str("}\n\n");

        out.push_str("/// The message-type slug for a known namespace: the tail of the\n");
        out.push_str("/// registry URN, e.g. `<prefix>order.001.001.01` → `order.001.001.01`.\n");
        out.push_str("pub fn message_type_of(namespace: &str) -> Option<&'static str> {\n");
        out.push_str("    schema_for(namespace).map(|s| s.message_type)\n");
        out.push_str("}\n\n");

        out.push_str("/// Decode by sniffing the document element's namespace.\n");
        out.push_str("pub fn decode(xml: &[u8]) -> Result<Decoded, DecodeError> {\n");
        out.push_str("    let (namespace, _root) = support::sniff_root(xml).map_err(DecodeError::NotWellFormed)?;\n");
        out.push_str("    decode_for_namespace(&namespace, xml)\n");
        out.push_str("}\n\n");

        out.push_str("/// Decode against the schema registered for `namespace`.\n");
        out.push_str("pub fn decode_for_namespace(namespace: &str, xml: &[u8]) -> Result<Decoded, DecodeError> {\n");
        out.push_str("    let schema = schema_for(namespace)\n");
        out.push_str("        .ok_or_else(|| DecodeError::UnknownNamespace { namespace: namespace.to_string() })?;\n");
        out.push_str("    let (document, violations) = support::decode_document(\n");
        out.push_str("        xml,\n");
        out.push_str("        schema.root_element,\n");
        out.push_str("        schema.namespace,\n");
        out.push_str("        schema.root_type,\n");
        out.push_str("        schema.types,\n");
        out.push_str("    )\n");
        out.push_str("    .map_err(DecodeError::NotWellFormed)?;\n");
        out.push_str("    Ok(Decoded {\n");
        out.push_str("        message_type: schema.message_type.to_string(),\n");
        out.push_str("        namespace: namespace.to_string(),\n");
        out.push_str("        document,\n");
        out.push_str("        violations,\n");
        out.push_str("    })\n");
        out.push_str("}\n\n");

        out.push_str(
            "/// Shape lookup across message types (deploy-time template-path checking).\n",
        );
        out.push_str("pub fn shape_of(message_type: &str, type_name: &str) -> Option<&'static [FieldShape]> {\n");
        out.push_str("    SCHEMAS\n");
        out.push_str("        .iter()\n");
        out.push_str("        .find(|s| s.message_type == message_type)\n");
        out.push_str("        .and_then(|s| (s.shape_of)(type_name))\n");
        out.push_str("}\n\n");

        out.push_str(
            "/// The root (document) type name for a message type, for `shape_of` entry.\n",
        );
        out.push_str("pub fn root_type_name(message_type: &str) -> Option<&'static str> {\n");
        out.push_str("    SCHEMAS\n");
        out.push_str("        .iter()\n");
        out.push_str("        .find(|s| s.message_type == message_type)\n");
        out.push_str("        .map(|s| s.root_type)\n");
        out.push_str("}\n");

        out
    }
}

// ---------------------------------------------------------------------------
// Slim field-declaration emission
// ---------------------------------------------------------------------------

/// The module-level `static` name for one schema's enum value table.
fn enum_static_name(enum_type: &str) -> String {
    format!("E_{enum_type}")
}

/// The `support::ScalarKind` variant for a neutral scalar (QName folds into `Text`,
/// matching the typed decoder's `decode_string` binding).
fn scalar_kind_variant(kind: Scalar) -> &'static str {
    match kind {
        Scalar::Boolean => "Boolean",
        Scalar::Int => "Int",
        Scalar::Decimal => "Decimal",
        Scalar::BigInt => "BigInt",
        Scalar::DateTime => "DateTime",
        Scalar::Duration => "Duration",
        Scalar::Bytes => "Bytes",
        // Text, QName
        _ => "Text",
    }
}

/// The `Content` expression and the `(str_facets, num_facets)` references for a field
/// plan — the slim analogue of `field_decl` + `decode_call_expr`.
fn field_content(p: &FieldPlan, pool: &mut FacetPool) -> (String, String, String) {
    let no_str = "&support::NO_STR_FACETS".to_string();
    let no_num = "&support::NO_NUM_FACETS".to_string();

    // Attributes: the typed decoder binds every attribute with `decode_attr_string`
    // (string + its str facets) regardless of declared type — match that.
    if p.fm.is_attribute {
        if p.skip {
            return ("support::Content::Skip".to_string(), no_str, no_num);
        }
        return (
            "support::Content::Scalar(support::ScalarKind::Text)".to_string(),
            pool.str_ref(&p.fm.facets),
            no_num,
        );
    }

    if p.skip {
        return ("support::Content::Skip".to_string(), no_str, no_num);
    }
    if let Some(enum_type) = p.enum_type {
        return (
            format!("support::Content::Enum({})", enum_static_name(enum_type)),
            no_str,
            no_num,
        );
    }
    if let Some(nested) = p.nested_type {
        return (
            format!("support::Content::Nested(\"{}\")", escape_rust(nested)),
            no_str,
            no_num,
        );
    }

    let scalar = p.scalar.expect("scalar plan carries a scalar kind");
    let content = format!(
        "support::Content::Scalar(support::ScalarKind::{})",
        scalar_kind_variant(scalar)
    );
    match scalar {
        // decode_string / decode_datetime / decode_base64 take the str facets.
        Scalar::Text | Scalar::QName | Scalar::DateTime | Scalar::Bytes => {
            (content, pool.str_ref(&p.fm.facets), no_num)
        }
        // decode_int / decode_decimal / decode_integer take the num facets.
        Scalar::Int | Scalar::Decimal | Scalar::BigInt => {
            (content, no_str, pool.num_ref(&p.fm.facets))
        }
        // decode_boolean / decode_duration are facet-free.
        Scalar::Boolean | Scalar::Duration => (content, no_str, no_num),
    }
}

/// Emit one `support::FieldDecl` row.
fn emit_field_decl(p: &FieldPlan, pool: &mut FacetPool, out: &mut String) {
    let slot = if p.fm.is_xml_value {
        "Value"
    } else if p.fm.is_attribute {
        "Attribute"
    } else {
        "Element"
    };
    let (content, str_ref, num_ref) = field_content(p, pool);
    w!(
        out,
        "            support::FieldDecl {{ xml: \"{}\", slot: support::Slot::{}, content: {}, required: {}, repeated: {}, str_facets: {}, num_facets: {} }},\n",
        escape_rust(&p.fm.xml_name),
        slot,
        content,
        p.fm.required,
        p.fm.is_list,
        str_ref,
        num_ref
    );
}

// ---------------------------------------------------------------------------
// Enum emission
// ---------------------------------------------------------------------------

fn emit_enum(em: &EnumModel, out: &mut String) {
    let mut used = HashSet::new();
    let variants: Vec<String> = em
        .values
        .iter()
        .map(|v| crate::names::sanitize_variant(&v.canonical_name, &mut used))
        .collect();

    out.push_str("#[derive(Debug, Clone, Copy, PartialEq, Eq)]\n");
    w!(out, "pub enum {} {{\n", em.name);
    for v in &variants {
        w!(out, "    {v},\n");
    }
    out.push_str("}\n\n");

    w!(out, "impl {} {{\n", em.name);
    out.push_str("    pub fn from_xml(value: &str) -> Option<Self> {\n");
    out.push_str("        match value {\n");
    for (i, v) in em.values.iter().enumerate() {
        w!(
            out,
            "            \"{}\" => Some(Self::{}),\n",
            escape_rust(&v.xml_value),
            variants[i]
        );
    }
    out.push_str("            _ => None,\n");
    out.push_str("        }\n");
    out.push_str("    }\n\n");
    out.push_str("    /// The canonical constant name — the contract's enum projection key.\n");
    out.push_str("    pub fn canonical_name(self) -> &'static str {\n");
    out.push_str("        match self {\n");
    for (i, v) in em.values.iter().enumerate() {
        w!(
            out,
            "            Self::{} => \"{}\",\n",
            variants[i],
            escape_rust(&v.canonical_name)
        );
    }
    out.push_str("        }\n");
    out.push_str("    }\n\n");
    out.push_str("    /// The XML enumeration value as written on the wire.\n");
    out.push_str("    pub fn xml_value(self) -> &'static str {\n");
    out.push_str("        match self {\n");
    for (i, v) in em.values.iter().enumerate() {
        w!(
            out,
            "            Self::{} => \"{}\",\n",
            variants[i],
            escape_rust(&v.xml_value)
        );
    }
    out.push_str("        }\n");
    out.push_str("    }\n");
    out.push_str("}\n\n");
}

// ---------------------------------------------------------------------------
// Class emission (struct + decode + map + shape row)
// ---------------------------------------------------------------------------

fn emit_class<'a>(
    cm: &'a ClassModel,
    class_names: &HashSet<&'a str>,
    enum_names: &HashSet<&'a str>,
    pool: &mut FacetPool,
    out: &mut String,
    shapes: &mut String,
) {
    let mut plans: Vec<FieldPlan<'a>> = Vec::new();
    let mut used_names: HashSet<String> = HashSet::new();
    let mut has_any = false;
    for fm in &cm.fields {
        if fm.is_any_element {
            has_any = true;
            continue;
        }
        if fm.is_mixed || fm.has_substitution_members {
            continue;
        }
        plans.push(plan_field(fm, class_names, enum_names, &mut used_names));
    }

    let is_choice = cm.xml_type_name.ends_with("Choice");

    let mut element_plans: Vec<&FieldPlan> = Vec::new();
    let mut attribute_plans: Vec<&FieldPlan> = Vec::new();
    let mut value_plan: Option<&FieldPlan> = None;
    for p in &plans {
        if p.fm.is_xml_value {
            value_plan = Some(p);
        } else if p.fm.is_attribute {
            attribute_plans.push(p);
        } else {
            element_plans.push(p);
        }
    }

    // ---- struct ----
    if let Some(doc) = &cm.javadoc {
        emit_doc_comment(out, doc, "");
    }
    out.push_str("#[derive(Debug, Clone, PartialEq, Default)]\n");
    w!(out, "pub struct {} {{\n", cm.name);
    for p in &plans {
        if p.skip {
            continue;
        }
        w!(out, "    pub {}: {},\n", p.rust_name, field_decl(p));
    }
    out.push_str("}\n\n");

    emit_decode_fn(
        cm,
        &element_plans,
        &attribute_plans,
        value_plan,
        has_any,
        is_choice,
        pool,
        out,
    );
    emit_map_fn(cm, &plans, out);
    emit_shape_row(cm, &plans, shapes);
}

fn field_decl(p: &FieldPlan) -> String {
    let base = if let Some(n) = p.nested_type {
        n.to_string()
    } else if let Some(e) = p.enum_type {
        e.to_string()
    } else {
        scalar_rust_type(p.scalar.unwrap()).to_string()
    };
    if p.fm.is_list {
        format!("Vec<{base}>")
    } else if p.nested_type.is_some() {
        format!("Option<Box<{base}>>")
    } else {
        format!("Option<{base}>")
    }
}

fn scalar_rust_type(kind: Scalar) -> &'static str {
    match kind {
        Scalar::Boolean => "bool",
        Scalar::Int => "i64",
        Scalar::Decimal | Scalar::BigInt => "bigdecimal::BigDecimal",
        Scalar::Bytes => "Vec<u8>",
        // Text, DateTime, Duration, QName
        _ => "String",
    }
}

// ---------------------------------------------------------------------------
// Decode function
// ---------------------------------------------------------------------------

#[allow(clippy::too_many_arguments)]
fn emit_decode_fn(
    cm: &ClassModel,
    element_plans: &[&FieldPlan],
    attribute_plans: &[&FieldPlan],
    value_plan: Option<&FieldPlan>,
    has_any: bool,
    is_choice: bool,
    pool: &mut FacetPool,
    out: &mut String,
) {
    let mutates_out = value_plan.is_some()
        || attribute_plans.iter().any(|p| !p.skip)
        || element_plans.iter().any(|p| !p.skip);

    w!(
        out,
        "pub fn decode_{}(node: &support::XmlNode, path: &str, ctx: &mut support::Ctx) -> {} {{\n",
        snake_case(&cm.name),
        cm.name
    );
    w!(
        out,
        "    let {}out = {}::default();\n",
        if mutates_out { "mut " } else { "" },
        cm.name
    );

    // Attributes.
    if attribute_plans.is_empty() {
        out.push_str("    support::check_attributes(node, &[], path, ctx);\n");
    } else {
        out.push_str("    const ATTRS: &[support::AttrSpec] = &[\n");
        for p in attribute_plans {
            w!(
                out,
                "        support::AttrSpec {{ name: \"{}\", required: {} }},\n",
                escape_rust(&p.fm.xml_name),
                p.fm.required
            );
        }
        out.push_str("    ];\n");
        out.push_str("    support::check_attributes(node, ATTRS, path, ctx);\n");
        for p in attribute_plans {
            if p.skip {
                continue;
            }
            w!(
                out,
                "    out.{} = support::decode_attr_string(node, \"{}\", path, {}, ctx);\n",
                p.rust_name,
                escape_rust(&p.fm.xml_name),
                pool.str_ref(&p.fm.facets)
            );
        }
    }

    // Element content model.
    if has_any {
        out.push_str("    // xs:any content — accepted without structural checks (wildcard).\n");
    } else if element_plans.is_empty() {
        out.push_str("    support::check_structure(node, &[], false, path, ctx);\n");
    } else {
        out.push_str("    const ELEMS: &[support::ElemSpec] = &[\n");
        for p in element_plans {
            w!(
                out,
                "        support::ElemSpec {{ name: \"{}\", required: {}, repeated: {} }},\n",
                escape_rust(&p.fm.xml_name),
                p.fm.required,
                p.fm.is_list
            );
        }
        out.push_str("    ];\n");
        if is_choice {
            out.push_str("    support::check_choice(node, ELEMS, path, ctx);\n");
        } else {
            out.push_str("    support::check_structure(node, ELEMS, false, path, ctx);\n");
        }
    }

    // simpleContent value.
    if let Some(vp) = value_plan {
        if !vp.skip {
            w!(
                out,
                "    out.{} = {};\n",
                vp.rust_name,
                decode_call_expr(vp, "node", "path", pool)
            );
        }
    }

    // Child element dispatch.
    let decoded: Vec<&&FieldPlan> = element_plans.iter().filter(|p| !p.skip).collect();
    if decoded.len() == 1 {
        let p = decoded[0];
        out.push_str("    for child in &node.children {\n");
        if p.fm.is_list {
            w!(
                out,
                "        if child.name == \"{}\" {{\n",
                escape_rust(&p.fm.xml_name)
            );
            emit_list_decode_body(p, pool, out, "            ");
            out.push_str("        }\n");
        } else {
            w!(
                out,
                "        if child.name == \"{}\" && out.{}.is_none() {{\n",
                escape_rust(&p.fm.xml_name),
                p.rust_name
            );
            emit_single_decode_body(p, pool, out, "            ");
            out.push_str("        }\n");
        }
        out.push_str("    }\n");
    } else if decoded.len() > 1 {
        out.push_str("    for child in &node.children {\n");
        out.push_str("        match child.name.as_str() {\n");
        for p in &decoded {
            if p.fm.is_list {
                w!(
                    out,
                    "            \"{}\" => {{\n",
                    escape_rust(&p.fm.xml_name)
                );
                emit_list_decode_body(p, pool, out, "                ");
            } else {
                w!(
                    out,
                    "            \"{}\" if out.{}.is_none() => {{\n",
                    escape_rust(&p.fm.xml_name),
                    p.rust_name
                );
                emit_single_decode_body(p, pool, out, "                ");
            }
            out.push_str("            }\n");
        }
        out.push_str("            _ => {}\n");
        out.push_str("        }\n");
        out.push_str("    }\n");
    }

    out.push_str("    out\n");
    out.push_str("}\n\n");
}

fn emit_single_decode_body(p: &FieldPlan, pool: &mut FacetPool, out: &mut String, indent: &str) {
    let xml = escape_rust(&p.fm.xml_name);
    w!(
        out,
        "{indent}let p = support::child_path(path, \"{xml}\", None);\n"
    );
    if let Some(nested) = p.nested_type {
        w!(
            out,
            "{indent}out.{} = Some(Box::new(decode_{}(child, &p, ctx)));\n",
            p.rust_name,
            snake_case(nested)
        );
    } else {
        w!(
            out,
            "{indent}out.{} = {};\n",
            p.rust_name,
            decode_call_expr(p, "child", "&p", pool)
        );
    }
}

fn emit_list_decode_body(p: &FieldPlan, pool: &mut FacetPool, out: &mut String, indent: &str) {
    let xml = escape_rust(&p.fm.xml_name);
    w!(
        out,
        "{indent}let p = support::child_path(path, \"{xml}\", Some(out.{}.len()));\n",
        p.rust_name
    );
    if let Some(nested) = p.nested_type {
        w!(
            out,
            "{indent}let item = decode_{}(child, &p, ctx);\n",
            snake_case(nested)
        );
        w!(out, "{indent}out.{}.push(item);\n", p.rust_name);
    } else {
        w!(
            out,
            "{indent}if let Some(v) = {} {{\n",
            decode_call_expr(p, "child", "&p", pool)
        );
        w!(out, "{indent}    out.{}.push(v);\n", p.rust_name);
        w!(out, "{indent}}}\n");
    }
}

/// The scalar/enum decode call for a plan (an `Option<T>` expression).
fn decode_call_expr(p: &FieldPlan, node_var: &str, path_var: &str, pool: &mut FacetPool) -> String {
    if let Some(enum_type) = p.enum_type {
        return format!("support::decode_enum({node_var}, {path_var}, {enum_type}::from_xml, ctx)");
    }
    let f = &p.fm.facets;
    match p.scalar.unwrap() {
        Scalar::Boolean => format!("support::decode_boolean({node_var}, {path_var}, ctx)"),
        Scalar::Int => {
            format!(
                "support::decode_int({node_var}, {path_var}, {}, ctx)",
                pool.num_ref(f)
            )
        }
        Scalar::Decimal => {
            format!(
                "support::decode_decimal({node_var}, {path_var}, {}, ctx)",
                pool.num_ref(f)
            )
        }
        Scalar::BigInt => {
            format!(
                "support::decode_integer({node_var}, {path_var}, {}, ctx)",
                pool.num_ref(f)
            )
        }
        Scalar::DateTime => {
            format!(
                "support::decode_datetime({node_var}, {path_var}, {}, ctx)",
                pool.str_ref(f)
            )
        }
        Scalar::Duration => format!("support::decode_duration({node_var}, {path_var}, ctx)"),
        Scalar::Bytes => {
            format!(
                "support::decode_base64({node_var}, {path_var}, {}, ctx)",
                pool.str_ref(f)
            )
        }
        // Text, QName
        _ => format!(
            "support::decode_string({node_var}, {path_var}, {}, ctx)",
            pool.str_ref(f)
        ),
    }
}

// ---------------------------------------------------------------------------
// Map projection function
// ---------------------------------------------------------------------------

fn emit_map_fn(cm: &ClassModel, plans: &[FieldPlan], out: &mut String) {
    let projected: Vec<&FieldPlan> = plans.iter().filter(|p| !p.skip).collect();

    let param = if projected.is_empty() { "_v" } else { "v" };
    w!(
        out,
        "pub fn map_{}({param}: &{}) -> support::MapValue {{\n",
        snake_case(&cm.name),
        cm.name
    );
    if projected.is_empty() {
        out.push_str("    support::MapValue::Map(Vec::new())\n");
        out.push_str("}\n\n");
        return;
    }
    out.push_str("    let mut m: Vec<(String, support::MapValue)> = Vec::new();\n");
    for p in &projected {
        let key = escape_rust(&p.fm.xml_name);
        let map_key = if p.fm.is_xml_value {
            "value".to_string()
        } else {
            key
        };
        if p.fm.is_list {
            w!(
                out,
                "    support::push_group(&mut m, \"{}\", v.{}.iter().map({}).collect());\n",
                map_key,
                p.rust_name,
                list_item_mapper(p)
            );
        } else if let Some(nested) = p.nested_type {
            w!(out, "    if let Some(x) = &v.{} {{\n", p.rust_name);
            w!(
                out,
                "        m.push((\"{}\".to_string(), map_{}(x)));\n",
                map_key,
                snake_case(nested)
            );
            out.push_str("    }\n");
        } else if p.enum_type.is_some() {
            w!(out, "    if let Some(x) = v.{} {{\n", p.rust_name);
            w!(
                out,
                "        m.push((\"{}\".to_string(), support::MapValue::Str(x.canonical_name().to_string())));\n",
                map_key
            );
            out.push_str("    }\n");
        } else {
            match p.scalar.unwrap() {
                Scalar::Boolean => {
                    w!(out, "    if let Some(x) = v.{} {{\n", p.rust_name);
                    w!(
                        out,
                        "        m.push((\"{}\".to_string(), support::MapValue::Bool(x)));\n",
                        map_key
                    );
                    out.push_str("    }\n");
                }
                Scalar::Int => {
                    w!(out, "    if let Some(x) = v.{} {{\n", p.rust_name);
                    w!(
                        out,
                        "        m.push((\"{}\".to_string(), support::MapValue::Int(x)));\n",
                        map_key
                    );
                    out.push_str("    }\n");
                }
                Scalar::Decimal | Scalar::BigInt => {
                    w!(out, "    if let Some(x) = &v.{} {{\n", p.rust_name);
                    w!(out, "        m.push((\"{}\".to_string(), support::MapValue::Dec(x.clone())));\n", map_key);
                    out.push_str("    }\n");
                }
                Scalar::Bytes => {
                    w!(out, "    if let Some(x) = &v.{} {{\n", p.rust_name);
                    w!(out, "        m.push((\"{}\".to_string(), support::MapValue::Bytes(x.clone())));\n", map_key);
                    out.push_str("    }\n");
                }
                _ => {
                    w!(out, "    if let Some(x) = &v.{} {{\n", p.rust_name);
                    w!(out, "        m.push((\"{}\".to_string(), support::MapValue::Str(x.clone())));\n", map_key);
                    out.push_str("    }\n");
                }
            }
        }
    }
    out.push_str("    support::MapValue::Map(m)\n");
    out.push_str("}\n\n");
}

/// Closure / fn-path mapping one list item to a MapValue.
fn list_item_mapper(p: &FieldPlan) -> String {
    if let Some(nested) = p.nested_type {
        return format!("map_{}", snake_case(nested));
    }
    if p.enum_type.is_some() {
        return "|x| support::MapValue::Str(x.canonical_name().to_string())".to_string();
    }
    match p.scalar.unwrap() {
        Scalar::Boolean => "|x| support::MapValue::Bool(*x)".to_string(),
        Scalar::Int => "|x| support::MapValue::Int(*x)".to_string(),
        Scalar::Decimal | Scalar::BigInt => "|x| support::MapValue::Dec(x.clone())".to_string(),
        Scalar::Bytes => "|x| support::MapValue::Bytes(x.clone())".to_string(),
        _ => "|x| support::MapValue::Str(x.clone())".to_string(),
    }
}

// ---------------------------------------------------------------------------
// Shape metadata
// ---------------------------------------------------------------------------

fn emit_shape_row(cm: &ClassModel, plans: &[FieldPlan], shapes: &mut String) {
    w!(shapes, "    (\"{}\", &[\n", escape_rust(&cm.name));
    for p in plans {
        if p.skip {
            continue;
        }
        let name = if p.fm.is_xml_value {
            "value"
        } else {
            &p.fm.xml_name
        };
        let (kind, type_name) = if p.fm.is_list {
            (
                "List",
                p.nested_type
                    .map(str::to_string)
                    .unwrap_or_else(|| scalar_shape_name(p)),
            )
        } else if let Some(nested) = p.nested_type {
            ("Nested", nested.to_string())
        } else {
            ("Scalar", scalar_shape_name(p))
        };
        w!(
            shapes,
            "        support::FieldShape {{ name: \"{}\", kind: support::FieldKind::{}, type_name: \"{}\" }},\n",
            escape_rust(name),
            kind,
            escape_rust(&type_name)
        );
    }
    shapes.push_str("    ]),\n");
}

fn scalar_shape_name(p: &FieldPlan) -> String {
    if p.enum_type.is_some() {
        return "string".to_string();
    }
    match p.scalar.unwrap() {
        Scalar::Boolean => "boolean",
        Scalar::Int | Scalar::BigInt => "integer",
        Scalar::Decimal => "decimal",
        Scalar::DateTime => "datetime",
        Scalar::Bytes => "bytes",
        _ => "string",
    }
    .to_string()
}

// ---------------------------------------------------------------------------
// Field planning
// ---------------------------------------------------------------------------

fn plan_field<'a>(
    fm: &'a FieldModel,
    class_names: &HashSet<&'a str>,
    enum_names: &HashSet<&'a str>,
    used_names: &mut HashSet<String>,
) -> FieldPlan<'a> {
    let base = if fm.is_xml_value {
        "value"
    } else {
        fm.xml_name.as_str()
    };
    let mut name = snake_case(base);
    while used_names.contains(&name) {
        name = format!("{name}_2");
    }
    used_names.insert(name.clone());

    let mut plan = FieldPlan {
        fm,
        rust_name: name,
        scalar: None,
        enum_type: None,
        nested_type: None,
        skip: false,
    };

    match &fm.field_type {
        FieldType::Scalar(scalar) => plan.scalar = Some(*scalar),
        FieldType::Opaque => plan.skip = true,
        FieldType::Named(name) => {
            let name = name.as_str();
            if enum_names.contains(name) {
                plan.enum_type = enum_names.get(name).copied();
            } else if class_names.contains(name) {
                plan.nested_type = class_names.get(name).copied();
            } else {
                // Cross-schema or unresolvable reference — kept in the structural
                // specs (so its element is not "unexpected") but not decoded.
                plan.skip = true;
            }
        }
    }
    plan
}

fn emit_doc_comment(out: &mut String, text: &str, indent: &str) {
    for line in text.split('\n') {
        let line = line.trim_end_matches('\r').trim();
        w!(out, "{indent}/// {line}\n");
    }
}

// ---------------------------------------------------------------------------
// Facet constant pool
// ---------------------------------------------------------------------------

/// Deduplicates facet sets into module-level `static` constants (`F_S…` string facets,
/// `F_N…` numeric facets), numbered by first-encounter order.
struct FacetPool {
    str_names: Vec<String>,
    str_by_key: std::collections::HashMap<String, String>,
    num_names: Vec<String>,
    num_by_key: std::collections::HashMap<String, String>,
    by_name: std::collections::HashMap<String, crate::model::Facets>,
}

impl FacetPool {
    fn new() -> FacetPool {
        FacetPool {
            str_names: Vec::new(),
            str_by_key: std::collections::HashMap::new(),
            num_names: Vec::new(),
            num_by_key: std::collections::HashMap::new(),
            by_name: std::collections::HashMap::new(),
        }
    }

    fn str_ref(&mut self, f: &crate::model::Facets) -> String {
        if !has_str_facets(f) {
            return "&support::NO_STR_FACETS".to_string();
        }
        let key = str_key(f);
        if let Some(name) = self.str_by_key.get(&key) {
            return format!("&{name}");
        }
        let name = format!("F_S{}", self.str_by_key.len());
        self.str_by_key.insert(key, name.clone());
        self.str_names.push(name.clone());
        self.by_name
            .entry(name.clone())
            .or_insert_with(|| f.clone());
        format!("&{name}")
    }

    fn num_ref(&mut self, f: &crate::model::Facets) -> String {
        if !has_num_facets(f) {
            return "&support::NO_NUM_FACETS".to_string();
        }
        let key = num_key(f);
        if let Some(name) = self.num_by_key.get(&key) {
            return format!("&{name}");
        }
        let name = format!("F_N{}", self.num_by_key.len());
        self.num_by_key.insert(key, name.clone());
        self.num_names.push(name.clone());
        self.by_name
            .entry(name.clone())
            .or_insert_with(|| f.clone());
        format!("&{name}")
    }

    fn emit(&self, out: &mut String) {
        for name in &self.str_names {
            let f = &self.by_name[name];
            w!(
                out,
                "static {name}: support::StrFacets = support::StrFacets {{ min_len: {}, max_len: {}, patterns: {} }};\n",
                opt_u32(eff_min(f)),
                opt_u32(eff_max(f)),
                patterns_expr(f)
            );
        }
        for name in &self.num_names {
            let f = &self.by_name[name];
            w!(
                out,
                "static {name}: support::NumFacets = support::NumFacets {{ min_inclusive: {}, max_inclusive: {}, min_exclusive: {}, max_exclusive: {}, total_digits: {}, fraction_digits: {}, patterns: {} }};\n",
                opt_str(f.min_inclusive.as_deref()),
                opt_str(f.max_inclusive.as_deref()),
                opt_str(f.min_exclusive.as_deref()),
                opt_str(f.max_exclusive.as_deref()),
                opt_u32(f.total_digits),
                opt_u32(f.fraction_digits),
                patterns_expr(f)
            );
        }
        if !self.str_names.is_empty() || !self.num_names.is_empty() {
            out.push('\n');
        }
    }
}

fn has_str_facets(f: &crate::model::Facets) -> bool {
    f.min_length.is_some() || f.max_length.is_some() || f.length.is_some() || !f.patterns.is_empty()
}

fn has_num_facets(f: &crate::model::Facets) -> bool {
    f.min_inclusive.is_some()
        || f.max_inclusive.is_some()
        || f.min_exclusive.is_some()
        || f.max_exclusive.is_some()
        || f.total_digits.is_some()
        || f.fraction_digits.is_some()
        || !f.patterns.is_empty()
}

fn eff_min(f: &crate::model::Facets) -> Option<i64> {
    f.length.or(f.min_length)
}

fn eff_max(f: &crate::model::Facets) -> Option<i64> {
    f.length.or(f.max_length)
}

fn opt_i64_key(v: Option<i64>) -> String {
    match v {
        Some(n) => n.to_string(),
        None => "null".to_string(),
    }
}

fn opt_str_key(v: Option<&str>) -> String {
    match v {
        Some(s) => s.to_string(),
        None => "null".to_string(),
    }
}

fn str_key(f: &crate::model::Facets) -> String {
    format!(
        "S|{}|{}|{}",
        opt_i64_key(eff_min(f)),
        opt_i64_key(eff_max(f)),
        f.patterns.concat()
    )
}

fn num_key(f: &crate::model::Facets) -> String {
    format!(
        "N|{}|{}|{}|{}|{}|{}|{}",
        opt_str_key(f.min_inclusive.as_deref()),
        opt_str_key(f.max_inclusive.as_deref()),
        opt_str_key(f.min_exclusive.as_deref()),
        opt_str_key(f.max_exclusive.as_deref()),
        opt_i64_key(f.total_digits),
        opt_i64_key(f.fraction_digits),
        f.patterns.concat()
    )
}

fn opt_u32(v: Option<i64>) -> String {
    match v {
        Some(n) => format!("Some({n})"),
        None => "None".to_string(),
    }
}

fn opt_str(v: Option<&str>) -> String {
    match v {
        Some(s) => format!("Some(\"{}\")", escape_rust(s)),
        None => "None".to_string(),
    }
}

fn patterns_expr(f: &crate::model::Facets) -> String {
    if f.patterns.is_empty() {
        return "&[]".to_string();
    }
    let mut sb = String::from("&[");
    for (i, p) in f.patterns.iter().enumerate() {
        if i > 0 {
            sb.push_str(", ");
        }
        w!(sb, "\"{}\"", escape_rust(p));
    }
    sb.push(']');
    sb
}
